### ISSUE TITLE
Glovo - The number of jobs posted on scrapers.peviitor.ro(24) is not the same as the number of jobs posted on the company's website (26)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#100]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Glovo"
3. Chech the number of jobs
4. Open https://jobs.glovoapp.com/find-your-ride/?l=romania
5. Chech the number of jobs

EXPECTED RESULTS:
The number of jobs is the same

ACTUAL RESULTS:
 The number of jobs posted on scrapers.peviitor.ro(24) is not the same as the number of jobs posted on the company's website (26)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8f41a39f-289a-4b1e-91c5-3bf387e39942)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f4518a43-cf2e-4f91-bec5-babb46d19f1b)

**Comment by lalalaurentiu** [comment]
Glove funcționează perfect. Bugul se afla în secțiunea lor de cariere unde 2 posturi ,care nu sunt din România, sunt afișate 
<img width="1440" alt="Screenshot 2023-10-23 at 02 42 37" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/c5ed2d94-f803-4d0d-b6f6-c8c79c61d529">

**Comment by AdrianaCionca** [comment]
The number of jobs posted on scrapers.peviitor.ro is  the same as the number of jobs posted on the company's website
