### ISSUE TITLE
Pentalog - 30 Jobs are displayed on-site instead of remote

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#101]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Pentalog"
3. Chech the jobs location
4. Open https://www.pentalog.com/jobs
5. Chech the jobs location

EXPECTED RESULTS:
30 of the 34 jobs displayed on scrapers.peviitor.ro are remote as on the company's website
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Pentalog"
3. Check the jobs location
4. Open https://www.pentalog.com/jobs
5. Check the jobs location

EXPECTED RESULTS:
30 of the 34 jobs displayed on scrapers.peviitor.ro are remote as on the company's website

ACTUAL RESULTS:
30 jobs are displayed on-site on scrapers.peviitor.ro instead of remote

ACTUAL RESULTS:
30 jobs are displayed on-site on scrapers.peviitor.ro instead of remote

Only 4 jobs are on-site:
- Oracle Database Administrator - Romania (Bucharest)
- Backup Engineer - Romania (Bucharest)
- Mainframe Support Production Engineer - Romania (Bucharest)
- SQL Database Administrator - Romania (Bucharest)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2aa440e1-941b-4cc6-bfee-74bd8e869ab7)

**Comment by lalalaurentiu** [comment]
Fixed!
