### ISSUE TITLE
Delonghi - The number of jobs posted on scrapers.peviitor.ro (4) and the one posted on the company website (10) isn't the same

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#103]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/delonghi/index.html
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "Run Scraper" button
3. See that 4 jobs are listed on https://scrapers.peviitor.ro/src/delonghi/index.html
4. Click on the "Delonghi Careers" button to open the Delonghi website with the listed jobs (https://www.delonghigroup.com/en/people/careers )
5. Select "Romania" in "Select Country" drop down list 
6. Count the jobs displayed (6)
7. Select "Romania ICT Hub" in "Select Country" drop down list
8. Count the jobs displayed (4)
9. Calculate the total number of jobs for filters "Romania" and "Romania ICT Hub" (10)
EXPECTED RESULTS:
The number of job listings displayed on scrapers.peviitor.ro should match the number of job listings available on the Delonghi website
ACTUAL RESULTS:
The number of job listings on scrapers.peviitor.ro after pressing Run Careers button differs from the number of job listings available on the Delonghi website.
<img width="1037" alt="Screenshot 2023-10-16 203645_nbr_jobs_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/f57c0efb-a0d6-4aa7-9964-e81d2b35526c">
<img width="1078" alt="Screenshot 2023-10-16 204019_delonghi" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/41d77113-67b1-4b69-9f2b-68ac539da77b">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Pe site-ul firmei sunt 2 optiuni de selectare a tarii (Romania si Romania ICT Hub). In total sunt 10 joburi , fata de 8 cat arata scraper-ul.

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by DanaCatavei** [comment]
![image](https://github.com/peviitor-ro/scrapers.js/assets/118441061/d59e9947-6600-4d02-a321-8eda11dfe41d)

Inca e bug.. Acum sunt 3 optiuni pe site-ul firmei pentru Romania, in total 8 joburi.
![image](https://github.com/peviitor-ro/scrapers.js/assets/118441061/05ad4662-c384-4b94-a992-50fd4129e1c8)
