### ISSUE TITLE
Delonghi - The number of jobs posted on peviitor.ro (4) and the one posted on the company website (10) isn't the same

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#104]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/delonghi/index.html
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "See jobs" button to open peviitor.ro website (https://peviitor.ro/rezultate?q=delonghi&country=Rom%C3%A2nia&page=1)
3. See that 4 jobs are listed on peviitor.ro website
4. Return to the web page with the URL
5. Click on the "Delonghi Careers" button to open the Delonghi website with the listed jobs (https://www.delonghigroup.com/en/people/careers)
6. Select "Romania" in "Select Country" drop down list 
7. Count the jobs displayed (6)
8. Select "Romania ICT Hub" in "Select Country" drop down list
9. Count the jobs displayed (4)
10. Calculate the total number of jobs for filters "Romania" and "Romania ICT Hub" (10)

EXPECTED RESULTS:
The number of job listings displayed on peviitor.ro should match the number of job listings available on the Delonghi website.
ACTUAL RESULTS:
The number of job listings on peviitor.ro differs from the number of job listings available on the Delonghi website.
<img width="1093" alt="Screenshot 2023-10-16 203745_peviitor" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/1b6f1095-45db-4a4d-a07f-cfa5eedcc5e6">
<img width="1078" alt="Screenshot 2023-10-16 204019_delonghi" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/8cd876fd-c87e-4d45-a43c-e2be064fcead">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Pe site-ul firmei sunt 2 optiuni de selectare a tarii (Romania si Romania ICT Hub). In total sunt 10 joburi , fata de 8 cat arata scraper-ul. Ramane bug!

**Comment by lalalaurentiu** [comment]
duplicate #103
