### ISSUE TITLE
Delonghi - Instead of the city, the message "Romania is not a city in Romania" is written

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#105]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/delonghi/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check cities for posted jobs
4. Open https://www.delonghigroup.com/en/people/careers and check the job location/city
EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website
1. Filter "Romania ICT Hub":

WEB DEVELOPER (M/F/X), Jucu, judetul Cluj
SENIOR WEB DEVELOPER (M/F/X), Cluj, judetul Cluj
FRONTEND DEVELOPER (M/F/X), Cluj, judetul Cluj
BACKEND DEVELOPER (M/F/X), Cluj, judetul Cluj

2. Filter "Romania":
TEST ENGINEER (M/F/X), Jucu, judetul Cluj
MES COORDINATOR (M/F/X), Jucu, judetul Cluj
ACADEMY PROGRAM FOR GRADUATES - DE'LONGHI GROUP ROMANIA, JUCU, judeul Cluj
CYBER SECURITY ADMINISTRATOR (M/F/X), Cluj, judetul Cluj
TEST ENGINEER COORDINATOR (M/F/X), Cluj, judetul Cluj
IT INFRASTRUCTURE ADMINISTRATOR (M/F/X), Cluj, Judetul Cluj

ACTUAL RESULTS:
Instead of the city, the message "Romania is not a city in Romania" is written
<img width="1037" alt="Screenshot 2023-10-16 203645_nbr_jobs_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/e1cf533d-da97-4475-a886-3d7bc867835c">
<img width="1001" alt="Screenshot 2023-10-16 224550_delonghi_city" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/fe1be9ee-0480-42a5-a96c-1f6499302655">

**Comment by lalalaurentiu** [comment]
Fixed!
