### ISSUE TITLE
BorgWarner - The city of the job is "Romania" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#109]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for BorgWarner Company
3. Check the city

EXPECTED RESULTS:
The city of the jobs is "Bucharest" as on the company's website

ACTUAL RESULTS:
 The city of the job is "Romania" instead of "Bucharest"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8f21b43a-d657-41b3-801b-8100cccdd142)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/5376cfe8-fae3-45d1-b0eb-db52778c4b5f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The city of the jobs is "Bucharest" as on the company's website
