### ISSUE TITLE
Michelin - Expired jobs ( 3 jobs) and jobs that are active on the Company website and are not in our database (2 jobs)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#110]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for Michelin Company
3. Check the jobs from "Voluntari" city
4. Open https://michelinhr.wd3.myworkdayjobs.com
5. Check the jobs from "Voluntari" city

EXPECTED RESULTS:
All solr.peviitor.ro  jobs are also active on the company's website

ACTUAL RESULTS:
 The following jobs are no longer active on the company website:

1. Junior Accountant with English
2. Procurer for Romanian plants with French/German
3. Invoicing Trainee

Jobs that are active on the Company website and are not in our database

1. Pricing Analyst with Spanish
2. Service and Solution Administrator with Hungarian
 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/e7ff12a7-494c-4b39-a112-6eb207f76f01)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2ac43eba-954b-47bc-82a8-a4cab7dd69a8)

**Comment by lalalaurentiu** [comment]
this job is no longer available
