### ISSUE TITLE
Michelin - The job title is not the same on solr.peviitor.ro as on the company website

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#111]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for Michelin Company
3. Check the job "Procurer for Poland" 
4. Open https://michelinhr.wd3.myworkdayjobs.com
5. Check the job "Procurer with Polish"

EXPECTED RESULTS:
The job title is the same on solr.peviitor.ro as on the company website

ACTUAL RESULTS:
The job title is not the same on solr.peviitor.ro as on the company website

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/9eb95f46-ad25-4858-a828-26dfc9e8fe9e)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f5cf06cd-e593-4c79-98e4-9e0487295e76)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The job title is the same on solr.peviitor.ro as on the company website - "Procurer with Polish"
