### ISSUE TITLE
Conarg - The "Conarg Careers" button does not open the careers page, it opens another company page where are no jobs available

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#114]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Conarg" Company
3. Click on the "Conarg Careers" button and check the jobs
4. Go to "Cariere" on the company website and open "Oportunitati de cariera"
5. Check the jobs 

EXPECTED RESULTS:
 The "Conarg Careers" button opens the careers page

ACTUAL RESULTS:
The "Conarg Careers" button does not open the careers page, it opens another company page, which has the title "available positions" but no job is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/78b1be6e-5858-45bf-9449-1dcd274a07f0)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2e777ed8-b447-4ba7-a109-9e8a1cc2ec49)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/be3c3fea-90c6-444f-879f-e5eeb2f41aaa)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The "Conarg Careers" button opens the careers page
