### ISSUE TITLE
Conarg - The city of the job is "Romania" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#115]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Conarg" Company
3. Check the cities of the jobs

EXPECTED RESULTS:
The city of the jobs is "Bucharest" as on the company's website

ACTUAL RESULTS:
 The city of the jobs is "Romania" instead of "Bucharest"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/bd5f01ea-efa7-4432-98b8-ff8b85396295)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/95a3057b-558f-4700-a148-910e1ad6f22c)

**Comment by lalalaurentiu** [comment]
Fixed!
