### ISSUE TITLE
Kontron - Incorrect transcription of the job title from the company website on solr.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#117]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Execute Query for Kontron Company
  3. Check the job title "14x7 Senior Engineer (Service Coordinator)"
  4. Open https://www.kontron.ro
  5. Check the job title"14x7 Senior Engineer (Service Coordinator)"

EXPECTED RESULTS:
The Job titles are written correctly

ACTUAL RESULTS:
The job title is different, "X" is used instead of "/"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/4c70bc49-c15b-4a10-82ca-45c60ba31251)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b90d5fb1-9efe-4ec2-8dd6-9bc5b22a599f)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/83b403d8-6cc3-4ba4-8016-079e8acda3da)

**Comment by lalalaurentiu** [comment]
Jobul are același titlu ca în secțiunea de cariere.
<img width="1440" alt="Screenshot 2023-10-28 at 16 00 59" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/ab3eaf17-dba8-49ab-9636-a8b635dee692">
Scraperul nu mai intra si în descrierea Jobului sa vadă dacă aia au scris la fel ca în secțiunea de cariere.
De aici ia screperul datele [Kontron](https://www.kontron.ro/Jobs.ro.html)
