### ISSUE TITLE
Cummins - The message "Dolj Craiova is not a city in Romania" is displayed 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#118]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Cummins" Company
3. Check the cities of the "eTime Analyst " job
4. Open https://cummins.jobs 
5. Check the job location for the "eTime Analyst " job

EXPECTED RESULTS:
The city/location of the job is "Dolj Craiova, Romania, Work Type: Hybrid - Potential for Partial Remote" as on the company's website

ACTUAL RESULTS:
The message "Dolj Craiova is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2fad7b8c-66c1-462b-9404-814affe0c0e3)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2025beb5-245d-481d-8001-5ddf556565b6)

**Comment by lalalaurentiu** [comment]
Fixed!
