### ISSUE TITLE
Plexus - The message " 9 Locations is not a city in Romania" is displayed

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#120]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Plexus" Company
3. Check the city of the "Project Manager - Construction" job
4. Open https://plexus.wd5.myworkdayjobs.com/en-US/Plexus_Careers/details/Program-Manager---Construction_R022818?locationCountry=f2e609fe92974a55a05fc1cdc2852122
5. Check the job location for the "Project Manager - Construction" job

EXPECTED RESULTS:
The city/location of the job is: Oradea, Romania and  Remote for the following countries: United States, Austria, Hungary, Germany and Ireland, as on the company's website

ACTUAL RESULTS:
The message "9 Locations is not a city in Romania" is displayed on scrapers.peviitor.ro and on solr.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ebc89bb8-bc77-4ba6-8633-a8dea9d49a3e)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/6f2bf363-551d-4434-ab17-dc8d9ccda873)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/32d2c4e6-e462-4fe3-9e3d-a618c32d3679)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/670e4cfe-5ec3-4826-bff9-16dc58a378b3)

**Comment by lalalaurentiu** [comment]
Scraperul funcționează normal, încearcă sa dai un clear cache la browser.
<img width="1440" alt="Screenshot 2023-10-30 at 23 10 55" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/757f1621-2cee-4bf3-adea-10943d826ad2">

**Comment by AdrianaCionca** [comment]
The number of jobs is not the same in scrapers.peviitor.ro and website Company (72 jobs), as in solr.peviitor.ro and peviitor.ro (68 jobs)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b43e1cee-2971-4f02-a4c1-be19b8a40590)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/d82ed4ac-107a-4f04-b275-4685ad71f2dc)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/c0ac689f-c2c0-4602-8532-b314f5b92817)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/9f881e30-0810-411a-89c8-9d72cbbd05f9)

**Comment by AdrianaCionca** [comment]
After retesting, the number of jobs is the same on solr.peviitor as on UI scrapers and the company website
