### ISSUE TITLE
Ikea -  The number of jobs posted on solr.peviitor.ro (0) is not the same as the number of jobs posted on the company's website (10)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#121]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Ikea" company
3. Chech the number of jobs
4. Open https://jobs.ikea.com/en/search-jobs/Romania/22908/2/798549/46/25/50/2
5. Chech the number of jobs

EXPECTED RESULTS:
The number of jobs posted on  solr.peviitor.ro is the same as the number of active jobs on the company website

ACTUAL RESULTS:
 The number of jobs posted on solr.peviitor.ro (0) is not the same as the number of jobs posted on the company's website (10)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/1f422c34-5e7b-4e7a-8be5-a78a4aa034e3)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/3eebf4b6-24c3-4cad-9df7-f751a02468a1)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/d22b795c-7033-49d0-9c4d-24fedca51bc7)

**Comment by lalalaurentiu** [comment]
Fixed!
