### ISSUE TITLE
Sanofi - The message "Praha, Budapest and Warsaw are not cities in Romania" is displayed

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#122]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Sanofi" Company
3. Check the cities of the jobs
4. Open https://en.jobs.sanofi.com/search-jobs/Romania
5. Check the job location for the jobs

EXPECTED RESULTS:
The city of the job is Bucharest as on the company's website

ACTUAL RESULTS:
The messages "Praha is not a city in Romania", "Budapest is not a city in Romania" and "Warsaw is not a city in Romania"  are displayed
On the company's website, there are multiple locations for a job and the scraper only picked up the first city

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/5ff18bd8-17bb-47f3-b666-4d3894df2aad)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/fb0e3c00-982b-49fe-8ed6-bf7f94cd628c)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/61446793-70fe-47ba-a031-30ceba066587)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/828bc56b-0ed3-44c5-a215-dba4567fecb1)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The number of jobs on scrapers.peviitor.ro (4 jobs) is not the same as the number of jobs on the company website (8 jobs)
4 of the jobs have multiple locations and were not taken over by the scraper

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f386b4b1-d469-4a69-a674-cf30db420a08)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/189dc1ab-4f5d-47e1-add2-cd17cf5afae4)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, the city of the 14 jobs is Bucharest, as on the company's website



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/71a05a01-c6b0-4834-af61-87615c104fc6)


![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ecb3b685-004e-48e1-b7b4-129215ef590e)
