### ISSUE TITLE
Cognizant -  The city of the job is "Romania" instead of "remote or hybrid" 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#123]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Cognizant" Company
3. Check the city of the jobs
4. Open https://scrapers.peviitor.ro/src/cognizantsoftvision/
5. Check the city of the jobs

EXPECTED RESULTS:
The city/place  of the jobs is "hybrid or remote" as on the company's website

ACTUAL RESULTS:
The city of the job is "Romania" instead of "remote or hybrid" on solr.peviitor.ro
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/da6cb690-2b16-4a1b-95ae-477aa8e1c3af)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/1001a807-5996-48d9-a268-2a558138e9b8)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/35e5c2c2-4acd-4d0c-94b4-181410604807)

**Comment by lalalaurentiu** [comment]
Fixed!
