### ISSUE TITLE
Leoni - All 22 jobs from solr.peviitor.ro are no longer available on the company website, but 9 other jobs are active on the company website

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#124]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Leoni" Company
3. Check the number and job titles
4. Open https://leoni.taleo.net/careersection/ro_romania
5. Check the number and job titles
6. Open https://scrapers.peviitor.ro 
7. Run scraper for "Leoni" Company
8. Click on "Vezi postul" for all the jobs

EXPECTED RESULTS:
The jobs from solr.peviitor.ro are active on the company's website

ACTUAL RESULTS:
All 22 jobs from solr.peviitor.ro are no longer available on the company website, but 9 other jobs are active on the company website
Active jobs can be seen in the screenshot

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b279b30c-eee0-4f22-a716-4d1dfa2dfff3)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/7e6917ae-a914-4165-ad11-72d9b17b3fd9)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/d9d11807-7f0d-4b1a-82dc-e32a34956041)

**Comment by lalalaurentiu** [comment]
fixed!

**Comment by AdrianaCionca** [comment]
All the jobs displayed in scrapers.peviitor,ro are no longer available

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/66b139e2-d13c-4b0e-aea9-2b976765adb0)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/d58b397c-dd74-45b3-9a9c-d7119d778b12)

**Comment by AdrianaCionca** [comment]
All 22 jobs from scrapers.peviitor.ro are no longer available on the company website, but 10 other jobs are active on the company website 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/72b78bd8-197a-4ea1-9d09-1e1b066597b8)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
The jobs that are located in "Bistrita" have the wrong county in solr.peviitor.ro. Valcea County is displayed instead of Bistrita-Nasaud County

![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b0cebfe5-e84b-4e24-b50f-1898788dfdb8)
