### ISSUE TITLE
SchneiderElectric - The city of the job is "Romania" instead of "remote or Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#128]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "SchneiderElectric" Company
3. Check the city of the jobs
4. Open https://careers.se.com/global/jobs?keywords=&lang=en-US&page=2&country=Romania
5. Check the city/location of the jobs

EXPECTED RESULTS:
The city/location of the jobs is "remote or Bucharest" as on the company's website

ACTUAL RESULTS:
The city of the job is "Romania" instead of "remote or Bucharest" on solr.peviitor.ro
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/79f27bce-dd26-461e-9060-38ad7ba27e8a)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/88268cb4-9594-45b7-8980-e9fe7dbeff61)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/14cf3636-7022-4c7d-9973-34cc0ee0a4e4)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, 7 of the 9 jobs that displayed "No job type" in scrapers.peviitor.ro, are remote on the company website

- Regional Cooling Service Expert,
- Utilities Segment Sales Manager, 
- Customer Advisor Trainee with Spanish , 
- Services Orders Admin Trainee, 
- Consulting Sustainability Advisor, 
- Sales Director – Industrial Automation EUs, OEMs & Industry SIs, 
- Commercial Customer Support with Bulgarian

![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/32144871-3f0a-469a-b0f9-324a9e5da9dc)




![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f813d7ab-eae3-427d-b664-579239e6b354)



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/446ea4f8-16e6-4d06-bb5d-2654401471d2)



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/1b514e20-dbd2-40e9-9e96-4ebbde7fab7d)



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/5a30484f-be82-44ed-a051-78e6d74d5a02)



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/e01c4c6e-1aa8-4380-8bc0-6e183778ace4)



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/62351848-3b98-477d-a211-5935bdde5273)
