### ISSUE TITLE
Loreal - The city of the job is "Romania" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#129]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Loreal" Company
3. Check the city of the jobs
4. Open https://careers.loreal.com
5. Check the city of the jobs

EXPECTED RESULTS:
The city/place  of the jobs is "Bucharest" as on the company's website

ACTUAL RESULTS:
The city of the job is "Romania" instead of "Bucharest" on solr.peviitor.ro
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/d66c57a2-1566-499d-8292-c8eff0986c56)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/18e65a4e-48b3-47a9-8a21-56431e342e0b)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2457a2b4-c344-4db8-a6d1-323f51f6460a)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
0 jobs after executing the query in solr.peviitor.ro and 7 jobs in scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f1ed3bd2-3dea-4b46-8348-6f6632e58ed0)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/5d15cc3a-372d-4dd6-a3f8-d01520c03560)

**Comment by lalalaurentiu** [comment]
Done!
<img width="1440" alt="Screenshot 2023-10-30 at 23 18 06" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/97131fb8-fe5e-4a98-8da9-620c696cbee2">
