### ISSUE TITLE
Majorel - Disabled jobs ( 6 out of 17 jobs displayed on the scrapers.peviitor.ro are disabled)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#134]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Majorel" Company
3. Check the jobs
4. Open https://jobs.majorel.com
5. Check the validity of the jobs

EXPECTED RESULTS:
All jobs displayed on scrapers.peviitor.ro are active on the company website

ACTUAL RESULTS:
The message "This vacancy posting has been deactivated" is displayed for the following jobs:

- Global Quality, Process and Training Manager 
- Senior IFRS Compliance Specialist 
- Cyber Security Consultant 
- Global Bid Coordinator – Pricing 
- Global Apps Senior Business Analyst 
- Global Apps Project Manager 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/44c519dd-430c-44c3-95b1-ab3b1c713c79)

**Comment by lalalaurentiu** [comment]
din joburile mentionate doar  "Global Apps Senior Business Analyst" a mai returnat screperul și este valid.

**Comment by AdrianaCionca** [comment]
The job "Technical Customer Support – Dutch" is Remote instead of "Bucuresti, Brasov, Sibiu" 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/c6f86bd1-0844-49f3-ad40-6489156cba07)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/02827913-3dbe-4b65-8b90-55b8518c41f6)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, all jobs displayed on scrapers.peviitor.ro are active on the company website
