### ISSUE TITLE
Pentasia - No active jobs in Bucharest like on solr.peviitor.ro and the remote ones are in Brasilia and Gibraltar

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#135]
NVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Pentasia" Company
3. Check the city of the jobs
4. Open https://www.pentasia.com/jobs/
5. Check the city of the jobs or if the jobs are remote

EXPECTED RESULTS:
The jobs are located in Bucharest or remotely

ACTUAL RESULTS:
 No active jobs in Bucharest like on solr.peviitor.ro and the remote ones are in Brasilia and Gibraltar

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ba6ea2b8-e083-47eb-8153-f893fc53f2fa)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/6de011e1-5ccd-4b7b-a74d-5edb171fa425)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/c5c8ff24-3d7a-4805-a3f5-75818d1d1a98)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The jobs are located in Bucharest or remotely
