### ISSUE TITLE
AIRBUS - Instead of the Bucuresti city, the message "Bucarest is not a city in Romania" is written

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#136]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/airbus/index.html
Browser: Chrome
Device: Desktop
OS: Windows 11

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Click on the "Run Scraper" button
3.See the location/city for jobs where "Bucarest is not a city in Romania" appears

EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website, but in romanian language and in accordance with the nomenclature of localities used.

Intern Artificial Intelligence Engineer, Bucuresti
Artificial Intelligence Engineer, Bucuresti
Senior Java Developer, Bucuresti

ACTUAL RESULTS:
Instead of the Bucuresti city, the message "Bucarest is not a city in Romania" is written
![Screenshot 2023-10-23 160303_scraper](https://github.com/peviitor-ro/scrapers.js/assets/118441061/e05aabbe-7a36-4dba-be71-d6b75ef8651f)
![Screenshot 2023-10-23 160828_airbus](https://github.com/peviitor-ro/scrapers.js/assets/118441061/7a15b34e-790b-4de5-921c-5065e3f0cb75)

**Comment by lalalaurentiu** [comment]
Astia nu stiu cum se scrie "București" în engleză 😆

**Comment by lalalaurentiu** [comment]
Fixed!
<img width="1440" alt="Screenshot 2023-10-30 at 23 14 29" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/1e45405a-d3d5-47f7-9f8a-baaf1b4e0387">

**Comment by DanaCatavei** [comment]
Verificat, OK! 
<img width="1052" alt="Screenshot 2023-11-02 130814" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/2736e081-0d34-46a0-8e20-6c249e947305">
