### ISSUE TITLE
FLEX - Instead of the Timisoara city, the message "Romania is not a city in Romania" is written 

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#137]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/flex/index.html
Browser: Chrome
Device: Desktop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check cities for posted jobs
4. Open https://flextronics.wd1.myworkdayjobs.com/ro-RO/Careers?Location_Country=f2e609fe92974a55a05fc1cdc2852122 and see that the city for jobs is Timisoara
EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website, namely Timisoara

ACTUAL RESULTS:
Instead of the Timisoara city, the message "Romania is not a city in Romania" is written
![Screenshot 2023-10-23 164422_scraper](https://github.com/peviitor-ro/scrapers.js/assets/118441061/66971598-11b1-4419-bb2f-155de68970ce)
![Screenshot 2023-10-23 164454_flex](https://github.com/peviitor-ro/scrapers.js/assets/118441061/fc8fd82d-69fa-4f12-8019-2d5c2e0b0dcb)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, Ok!
<img width="1099" alt="Screenshot 2023-11-02 132545" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/7bb781d9-330d-48d9-a757-4ba3b09329b6">
