### ISSUE TITLE
Porsche - The job locations on solr.peviitor.ro are not the same as the job locations on the company website

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#138]
NVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Porsche" Company
3. Check the city of the jobs
4. Open https://jobs.porsche.com
5. Check the city of the jobs 

EXPECTED RESULTS:
The jobs are located in Cluj, Timisoara, remote or combined location as on the company website

ACTUAL RESULTS:
Only 9 jobs out of 60 have a single location, the other 51 have multiple locations: Cluj and Timisoara or Cluj, Timisoara and remote on the website company.
In solr.peviitor.ro 51 jobs are located in Cluj and 9 in Timisoara

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ce54d5bd-efee-4f6a-81fc-5d7eba8cfb2c)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/3ba3ec55-30cc-4035-8d1e-2fd4d27ffdb4)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/a5d5c9e3-e27c-419c-b1a7-1502971beed5)

**Comment by lalalaurentiu** [comment]
Fixed!
