### ISSUE TITLE
ING - The number of jobs posted on scrapers.peviitor.ro (134) and the one posted on the company website (164) isn't the same 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#139]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Ing" company
3. Check the number of jobs
4. Open https://www.ing.jobs/global/careers/job-opportunities.htm?location_level_1=RO&
5. Check the number of jobs

EXPECTED RESULTS:
The number of jobs posted on  scrapers.peviitor.ro is the same as the number of active jobs on the company website

ACTUAL RESULTS:
The number of jobs posted on scrapers.peviitor.ro (134) and the one posted on the company website (164) isn't the same 
The message "Romania is not a city in Romania" is displayed 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/34fe1ee4-2bad-45f2-9b17-fb83283ed147)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/1f6546e6-6abd-4129-9c35-677dacf4e001)

**Comment by DanaCatavei** [comment]
Laurentiu, if it helps you, I attach an excel file with the jobs and related localities for ING.
[joburi_ing_localitati.xlsx](https://github.com/peviitor-ro/scrapers.js/files/13076273/joburi_ing_localitati.xlsx)

**Comment by lalalaurentiu** [comment]
L-am fixat parțial, nu pot sa iau orașele deoarece trebuie sa intru în fiecare pagina, sunt 155 de joburi din care doar 3 sunt în Cluj restul în București. Le-am trecut pe toate pe București. JS poate sa facă 155 de requesturi într-o secunda și asta e o problema deoarece site-ul poate detecta aceste requesturi sub forma de attack DDOS și mă poate bloca.
