### ISSUE TITLE
Yonder scraper needs fix, scraper use invalid links

### ISSUE THREAD

**Issue by TheMrM** [peviitor-ro/scrapers.js#14]
** ENVIREMENT: DEV **

URL: https://firme.peviitor.ro/
BROWSER: Chrome Version 114

** STEPS TO REPRODUCE **

1)Open URL in BROWSER
2)Type Yonder in search bar
3)Click on company logo
4)Click on job button "Vezi postul ->"

** EXPECTED RESULTS **

Link should return the job post
![yonderjob](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/29de7629-5b10-48c4-892b-adb4cb02bfdf)

** ACTUAL RESULTS **

Link is returning 404 or wrong URL
![yonder404](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/5eefa6dc-de2d-4790-86f7-00998c9a06b1)
![yonderjobJSEMLCJwrongtypelink](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/59c68bac-a6db-4571-a004-ae1ebb594339)

** Jobs that have a faulty link **

1 -  
![1PDSRiasi](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/41b03130-8ad0-4248-9e52-ed8d06ee236f)

2 -
![3WDSLcluj](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/5713f643-0e28-4a21-bd2d-adbe0970c874)

3 - 
![4PHPDEVSLCJ](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/02d4c50b-baaf-4fd3-bde1-eb7de70534d1)

4 -
![5WTLcluj](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/eee0294d-5667-4d6d-a7d4-72e34b90a1c5)

5 -
![15JSESLcluj](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/9acada56-be76-4b06-925c-8bddc0a69a18)

6 -
![16CEMScluj](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/79424d6d-c117-463f-8032-819050151141)

7 -
![19JSEMLCJ](https://github.com/peviitor-ro/based_scraper_py/assets/128375812/dee229f0-56ae-4e9a-877e-e8e918945244)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by TheMrM** [comment]
Same errors as of 30.07.2023 08:54AM
+ Missing company logo
