### ISSUE TITLE
Celestica - Instead of the Oradea city, the message "Oradea, BH, RO is not a city in Romania" is written 

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#141]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/celestica/index.html
Browser: Chrome
Device: Desktop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check cities for posted jobs
4. Open https://careers.celestica.com/search/?createNewAlert=false&q=&locationsearch=Romania and check the job location/city

EXPECTED RESULTS:
The city of the jobs is written in accordance with the city on the company website, namely

ACTUAL RESULTS:
Instead of the Oradea city, the message "Oradea, BH, RO is not a city in Romania" is written
![Screenshot 2023-10-23 224134_scraper](https://github.com/peviitor-ro/scrapers.js/assets/118441061/19cb6ca4-f418-4f12-a699-5854902efcfa)
![Screenshot 2023-10-23 225026_celestica](https://github.com/peviitor-ro/scrapers.js/assets/118441061/37a02c3f-f026-4f60-9236-fd615d3f6ac2)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, Ok!
<img width="1111" alt="Screenshot 2023-11-02 132139" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/ab35ba75-3747-45ef-8bff-cc4aca41734b">
