### ISSUE TITLE
Keysight - No open positions for Romania

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#142]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Keysight" company
3. Check the city of the jobs
4. Open https://jobs.keysight.com
5. Check the jobs for Romania
6. Open https://scrapers.peviitor.ro
7. Run scraper for "Keysight" Company 
8.  Check the city of the jobs

EXPECTED RESULTS:
The jobs in solr.peviitor.ro have Romanian cities as their location

ACTUAL RESULTS:
The jobs from solr.peviitor.ro are located in cities from other countries
In scrapers UI the message "Singapore, Rome, Penang, Hachioji  is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/774e697e-a5e4-47e2-adca-ee8bad722b94)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/96f98fcd-4fb1-40fb-a734-df03ff5df585)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/a0a06d4c-f5c9-42dd-a552-9a148c3f02e4)

**Comment by lalalaurentiu** [comment]
Fixed!
