### ISSUE TITLE
Philips - "Romania - Home Based"  instead "remote"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#143]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Philips" Company
3. Check the city for the job "Key Account Manager DI/IGT (North East Romania)"
4. Open https://philips.wd3.myworkdayjobs.com/en-US/jobs-and-careers
5. Search for the job "Key Account Manager DI/IGT (North East Romania)" and check the job location
6. Open https://scrapers.peviitor.ro and run scraper for "Philips" Company
7. Check the city for the job "Key Account Manager DI/IGT (North East Romania)"

EXPECTED RESULTS:
The city/location of the jobs is "remote" as on the company's website

ACTUAL RESULTS:
The city of the job is "Romania - Home based" instead of "remote" on solr.peviitor.ro
The message "Romania - Home Based is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/021514a5-ee4a-4581-a168-bac5d3a7f78a)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The job "Business Development Manager" is "remote" instead of "Bucharest" as on the company's website

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/975b0bfa-767e-477b-b363-e4157fd4b39e)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/9102a1ca-cb55-43ba-8ae5-b5ce7a303fe3)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, the jobs "Marketing & Sales Manager Emergency Care CEE" and "Trade Partner Manager Customer Service" are remote on scrapers.peviitor.ro instead of Bucharest as on the company website



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ef532945-10c1-4abf-9045-d48e8a16cca3)


![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/18f5d7da-8d12-49b5-b6ec-e33f016f1965)





![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/085f64cc-7758-4218-955f-aec6638f87e8)


![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/a6a2a665-eb90-43a3-9416-599746ac74f5)
