### ISSUE TITLE
Aptiv - Instead of the Ineu city, the message "Ineu-Arad is not a city in Romania" is written 

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#144]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/aptiv/index.html
Browser: Chrome
Device: Desktop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check cities for MPC Lean Coordinator & H&S Coordinator jobs
4. Open https://www.aptiv.com/en/jobs/search?country=Romania and see the job location/city is Ineu-Arad, but correct is Ineu from Arad county
EXPECTED RESULTS:
The city of the jobs is written in accordance with the city on the company website, namely Ineu

ACTUAL RESULTS:
Instead of the Ineu city, the message "Ineu-Arad is not a city in Romania" is written 
![Screenshot 2023-10-24 120938_scraper](https://github.com/peviitor-ro/scrapers.js/assets/118441061/7d280c1a-8a98-4ec0-9a32-b4f4332b4550)
![Screenshot 2023-10-24 121051_solr](https://github.com/peviitor-ro/scrapers.js/assets/118441061/22415e19-bc91-43a2-a231-96b2369bb930)
![Screenshot 2023-10-24 123250_aptiv](https://github.com/peviitor-ro/scrapers.js/assets/118441061/2b97613b-9f30-4f8e-bf12-5d5b531ad55f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, OK!
<img width="1084" alt="Screenshot 2023-11-02 131737" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/2ad0fe15-7327-43d4-ba8b-655d4852d4f4">
