### ISSUE TITLE
Qualitance - Instead of the city, the message "Romania is not a city in Romania" is written

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#145]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/qualitance/index.html
Browser: Chrome
Device: Desktop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check the cities in the job ad content or see below
4. Open https://qualitance.com/careers/?_gl=1*oyrkjd*_ga*Njg1MjU3NjQ4LjE2OTgxNDU0OTU.*_ga_0KFC21Y768*MTY5ODE0NTQ5NS4xLjEuMTY5ODE0NjA5OC40OS4wLjA. and check the city
EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website

Project Management Officer, Romania (!!! I really couldn't find the location in the job advertisement !!! )
Business Analyst (debts recovery),Romania (!!! I really couldn't find the location in the job advertisement !!! )
Test Manager, Bucharest
Senior Unity Developer,Bucharest
iOS Developer,Bucharest
ServiceNow Developer, Remote
Senior Technical Business Analyst, Bucharest
Java Full-Stack Developer, Remote
Senior Java Cloud Developer, Remote
AWS DevOps Engineer, Remote
Senior Java Engineer, Bucharest

ACTUAL RESULTS:
Instead of the city, the message "Romania is not a city in Romania" is written
![Screenshot 2023-10-24 143428_scraper](https://github.com/peviitor-ro/scrapers.js/assets/118441061/4720c2f6-e2ec-43c6-a012-42d0fa373247)
![Screenshot 2023-10-24 143637_qualitance](https://github.com/peviitor-ro/scrapers.js/assets/118441061/0a496910-361a-4973-add3-2fc1aef3f57c)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, OK!
<img width="1102" alt="Screenshot 2023-11-08 174656" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/e9672a0d-e055-430b-869e-b2087ac3f4ca">
