### ISSUE TITLE
Zf -  The city of the job is "Budapest" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#148]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Zf" Company
3. Check the city of the job "Sales Engineer (Romania)"

EXPECTED RESULTS:
The city of the jobs is "Bucharest" as on the company's website

ACTUAL RESULTS:
The city of the job is "Budapest" instead of "Bucharest"
On scrapers.peviitor.ro the message  "Budapest is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/0e5eafb6-dce1-42a9-92e1-8ece6658b95a)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/0c88b12f-f1e3-4794-ac82-d16fda7d00a7)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8a9107e2-f975-413e-8395-c3a59afc2256)

**Comment by lalalaurentiu** [comment]
Fixed!
