### ISSUE TITLE
AtlasCopco - The job location is "Bucharest" instead of "Bucharest - remote"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#149]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "AtlasCopco" Company
3. Check the location for "Sales Engineer - Romania" job
4. Open https://www.atlascopco.com/ro-ro/jobs/job-overview?keyword=romania
5. Check the location for "Sales Engineer - Romania" job

EXPECTED RESULTS:
The job location is "remote" as on the company's website

ACTUAL RESULTS:
The job location is "Bucharest" instead of "Bucharest - remote"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ee2cc0d6-5718-4e91-936d-42b8ed579d5b)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f653e69b-c2f7-4dbc-bde8-f4fa87437d04)

**Comment by lalalaurentiu** [comment]
That job is no longer available
