### ISSUE TITLE
  Decorfloor - The job location is "Romania" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#151]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Decorfloor" Company
3. Check the jobs location 
4. Open https://decorfloor.ro/careers
5. Check the jobs location 

EXPECTED RESULTS:
The job location is "Bucharest" as on the company's website

ACTUAL RESULTS:
The job location is "Romania" instead of "Bucharest"
On the scrapers.peviitor.ro the message "Romania is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b08d369a-29f7-4ef2-9d3c-f039d0addbe8)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/44fb26d7-2852-4ce4-aa71-e500fbf87906)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/77bf9459-772a-4650-b290-268ac0d8c9ba)

**Comment by lalalaurentiu** [comment]
Decât un singur job are afișata locația celelalte 2 le-am trecut în Cluj și București unde are firma sediul.
