### ISSUE TITLE
DeutscheBank - Inactive status when the scraper is running

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#152]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/deutschebank/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "Run Scraper" button
3. See the status of the scraper as inactive
EXPECTED RESULTS:
Status Activ and the list of valid jobs for the DeutscheBank company

ACTUAL RESULTS:
Inactive status when the scraper is running and the job list is not displayed
On the peviitor.ro page it is the same, there are no jobs displayed
<img width="1039" alt="Screenshot 2023-10-25 225743_scraper_inactiv" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/695bd0c6-e354-48f7-af6f-45f1efee1f93">
<img width="979" alt="Screenshot 2023-10-25 230113_solr" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/c269eeed-bb18-4288-baf7-14cddc36d591">
<img width="1092" alt="Screenshot 2023-10-25 230746_peviitor" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/e6a80e1e-3dc7-4b23-bd8e-cc5f208b5ae9">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, Ok!
<img width="1100" alt="Screenshot 2023-11-08 174944" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/4d850b92-2230-4064-92bc-c8fbb055ad7d">
