### ISSUE TITLE
Yonder - Inactive status when the scraper is running 

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#154]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/yonder/index.html
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "Run Scraper" button
3. See the status of the scraper as inactive
EXPECTED RESULTS:
Status Activ and the list of valid jobs for the Yonder company
ACTUAL RESULTS:
Inactive status when the scraper is running and the job list is not displayed
Solr and peviitor.ro works but does not match the number of jobs
<img width="982" alt="Screenshot 2023-10-26 130612_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/082a080c-336f-40ff-9337-26d7dbd37de5">
<img width="1096" alt="Screenshot 2023-10-26 131239_yonder" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/c52a4a52-3bd1-455d-a130-319212ad800e">
<img width="1064" alt="Screenshot 2023-10-26 131921_solr" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/d43946a0-071e-4949-a58f-86fb4d41a27d">
<img width="1057" alt="Screenshot 2023-10-26 131952_peviitor" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/5515662f-b803-4141-8ab1-2c7db95f0753">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, OK!
<img width="1114" alt="Screenshot 2023-11-08 182648" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/de0b3682-83e7-49c7-964c-9a01eca2bfe8">
