### ISSUE TITLE
Quanticlab- Inactive status when the scraper is running

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#155]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/quanticlab/index.html
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "Run Scraper" button
3. See the status of the scraper as inactive
EXPECTED RESULTS:
Status Activ
ACTUAL RESULTS:
Inactive status when the scraper is running 
Solr and peviitor.ro works but no jobs were found, as on the Quanticlab site (https://www.quanticlab.com/career/)
<img width="1012" alt="Screenshot 2023-10-26 133526_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/6bed449a-f585-4f38-87d4-8ca9ca01c0c4">
<img width="1097" alt="Screenshot 2023-10-26 133602_quanticlab" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/3d2da7a1-ac3e-4418-a749-19f4ed12d1cb">
<img width="1093" alt="Screenshot 2023-10-26 133649_solr" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/e8b01e69-fe09-44c5-8bd3-547dffb8f635">
<img width="1067" alt="Screenshot 2023-10-26 133736_peviitor" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/630eccaa-2445-455a-a3b7-5c517191df5c">

**Comment by lalalaurentiu** [comment]
ma voi ocupa de el când vor fi joburi disponibile.

**Comment by DanaCatavei** [comment]
In asteptare! Nu sunt job-uri disponibile!
