### ISSUE TITLE
 Continental - The number of jobs posted on https://solr.peviitor.ro (153) is not the same as the number of jobs posted on the company's website (322)

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#156]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Continental" company
3. Check the number of jobs
4. Open https://jobs.continental.com/en/#/?locationSuggestChecksums=97df691231f6e638f96c63c52454e425&sorting=cityLabel_stringS%20ASC
5. Check the number of jobs
EXPECTED RESULTS:
The number of jobs is the same 

ACTUAL RESULTS:
The number of jobs posted on https://solr.peviitor.ro (153) is not the same as the number of jobs posted on the company's website (322)
On peviitor.ro page is the same
<img width="1070" alt="Screenshot 2023-10-26 135618_solr" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/5ab8856c-836c-4194-8434-06d4f749021e">
<img width="1076" alt="Screenshot 2023-10-26 135308_continental" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/5d5a565c-ecb8-4856-a5a4-f2ea0588dc59">
<img width="1074" alt="Screenshot 2023-10-26 135652_peviitor" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/3614d2cd-524a-4b3e-aa3c-302fbefe0d64">
<img width="1070" alt="Screenshot 2023-10-26 135731_scaper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/1ca5f1ab-b831-4d8f-82a3-f4646e905af3">

**Comment by lalalaurentiu** [comment]
Fixed!
