### ISSUE TITLE
Revolut - The job location is "Romania" instead of "Remote"

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#157]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Execute Query for "Revolut" Company
3.Check the location for all jobs
4.Open https://www.revolut.com/careers/?city=Romania+-+Remote
5.Check the location for all jobs
EXPECTED RESULTS:
The job location is "remote" as on the company's website

ACTUAL RESULTS:
The job location is "Romania" instead of "Remote"
<img width="1047" alt="Screenshot 2023-10-26 140515_solr" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/117ed6e6-3c7e-4c0f-9553-dcbefa2f0632">
<img width="1088" alt="Screenshot 2023-10-26 140630_revolut" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/2b9c299e-615f-4b17-a5eb-1784a2a819e8">
<img width="1103" alt="Screenshot 2023-10-26 140444_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/2a87cd7f-516c-4dac-9bc4-acfd1246fd49">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Partial fixat.
Solr, Ok!
Peviitor, OK!
scrapers.peviitor.ro, Database Error!

<img width="963" alt="Screenshot 2023-11-08 183832" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/33309b69-fb3a-4f8f-8b86-015b772093e8">
<img width="1086" alt="Screenshot 2023-11-08 183841" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/d3532ca0-fb43-4444-a1ae-c1a21db87944">
<img width="1055" alt="Screenshot 2023-11-08 183859" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/44bddc78-40ac-4bc6-bff3-b20a1b9c87b8">
