### ISSUE TITLE
IBM - Job locations are not the same on solr.peviitor as they are on the company website

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#158]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "IBM" Company
3. Check the city of the jobs
4. Open https://www.ibm.com/careers
5. . Check the city of the jobs

EXPECTED RESULTS:
The location of the jobs are the same on solr.peviitor.ro as on the company website
47 of the jobs have multiple locations as on the company website: Bucharest, Brasov, Cluj-Napoca, Timisoara
20 of the jobs have "Bucharest" as location
  1 job has "Timisoara" as location

ACTUAL RESULTS:
Job locations are not the same on solr.peviitor as they are on the company website
 46 of the jobs have "Brasov" as location
 21 of the jobs have "Romania" as location
   1 job has "Bucharest" as location

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/5dec917c-d2fa-47dd-90aa-34f83d5f8382)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/19c382fa-1626-4bc8-a1ff-80528ec85fdd)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f5858ae7-547a-4e43-89c4-36ccfb2ee978)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8ca07019-15fc-43ca-a161-aa6ea3889b9f)

**Comment by lalalaurentiu** [comment]
Fixed!
