### ISSUE TITLE
Dynata - The city of the jobs is "Romania" instead of "Timisoara, hybrid or remote" as on the company's website

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#159]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Dynata" Company
3. Check the city of the jobs

EXPECTED RESULTS:
The city of the jobs is "Timisoara, hybrid or remote" as on the company's website

- Survey Programmer - Timisoara, On-site
- Accounts Receivable Coordinator with Spanish or Italian - Timisoara, Hybrid
- Account Manager - Timisoara, Hybrid
- Accounts Receivable Coordinator with German -Timisoara, On-site
- Lead, Data Science - Fully Remote

ACTUAL RESULTS:
The city of the jobs is "Romania" instead of "Timisoara, hybrid or remote" like on the website company
On scrapers.peviitor.ro the message  "Romania is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/4ac7a1ed-dbb3-4170-a085-67cfc2128c48)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/1d59c8fe-beba-4bca-8325-197f7a399cfd)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/14e0a170-e9de-4a18-a2bf-0f35cbbf5f9e)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/5ec7dc28-b4f1-4c90-a36e-7269c8db295e)

**Comment by lalalaurentiu** [comment]
Fixed!
