### ISSUE TITLE
Mondelez - The job location is "Romania/7 location/16 location" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#162]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Mondelez" Company
3. Check the jobs location 
4. Open https://www.mondelezinternational.com/Careers/Jobs/?term=&countrycode=RO
5. Check the jobs location 

EXPECTED RESULTS:
The job location is "Bucharest" as on the company's website

ACTUAL RESULTS:
The job location is "Romania/7 location/16 location" instead of "Bucharest"
On the scrapers.peviitor.ro the messages "Romania is not a city in Romania" , "7 Locations is not a city in Romania" and "16 Locations is not a city in Romania" are displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b8a08572-caee-477e-8177-e98a9219f8ae)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/7123dca7-aa88-4935-8246-ed6408a2da0a)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/c6461461-6289-4789-9ea3-a82b0cbebc03)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/fa10d8fa-935b-440b-be29-9aeb0c243b40)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The job "Data Architect" is located in Bucharest on scrapers.peviitor.ro instead of "remote"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/e01916c7-b56f-4b07-9150-5d6c7a660b91)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/aa4eb98e-93be-4fc4-8468-b43ff6bcfa35)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, the job "Data Architect" is no longer part of the company's job offer
