### ISSUE TITLE
Hilti - "Dragomiresti Vale" and "Dragomiresti Deal" are listed as cities instead of communes

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#163]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Hilti" Company
3. Check the jobs location 
4. Open https://careers.hilti.group
5. Check the jobs location 

EXPECTED RESULTS:
Dragomiresti Vale and Dragomiresti Deal are communes, not cities

ACTUAL RESULTS:
- In https://solr.peviitor.ro "Dragomiresti Vale" and "Dragomiresti Deal" are listed as towns, but they are communes, not towns
- On the scrapers.peviitor.ro the messages "Dragomiresti Deal is not a city in Romania" and "Dragomiresti Vale is not a city in Romania" are displayed.
- The message "Bucuresti Ilfov is not a city in Romania" are displayed for the job "Tehnician electromecanic"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8e084a08-9f47-4ec3-935a-acf93f347f80)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f0ffcea9-0a92-4363-a7d2-64f4347bc963)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/69439195-acce-44e5-90fd-a70a2eed1499)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/22825705-4dd2-4799-9ee9-ed314cf326a1)

**Comment by lalalaurentiu** [comment]
Fixed!
