### ISSUE TITLE
Zollnar - The number of jobs posted on https://solr.peviitor.ro (18) is not the same as the number of jobs posted on the company's website (21)

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#164]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Zollnar" company (18)
3. Check the number of jobs
4. Open https://www.zollner.ro/ro/cariera/posturi-disponibile (21)
5. Count the jobs
EXPECTED RESULTS:
The number of jobs is the same
The city of the jobs is "Romania" instead of "Satu Mare"
See the excel file with Zollnar's jobs and their locations
[joburi Zollnar.xlsx](https://github.com/peviitor-ro/scrapers.js/files/13195542/joburi.Zollnar.xlsx)

ACTUAL RESULTS:
The number of jobs posted on https://solr.peviitor.ro (18) is not the same as the number of jobs posted on the company's website (21)
On peviitor.ro page is the same, the number of jobs is not the same as on the company website
The locality must be the same as in the job advertisement on the Zollnar website, namley Satu Mare
<img width="943" alt="Screenshot 2023-10-28 125017_solr" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/558ecf5d-e84f-4f4f-83b2-9940a8269baa">
<img width="1082" alt="Screenshot 2023-10-28 133937_zollnar" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/ca33ee90-175f-44c8-8300-ddf258abf139">
<img width="892" alt="Screenshot 2023-10-28 124714_peviitor" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/b52d378d-cfca-4c53-9998-6fb2a50865ed">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, OK!

<img width="1074" alt="Screenshot 2023-11-08 184633" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/e760d28b-2763-430c-98d5-d7908fd8f253">
<img width="1094" alt="Screenshot 2023-11-08 184643" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/de5b2310-1fe0-448f-acdd-44166fee9739">
<img width="987" alt="Screenshot 2023-11-08 184718" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/5259cd51-a068-486f-b305-63003755389b">
