### ISSUE TITLE
Techtalent - The job location is "remote/no city/Cluj/Bucuresti/Brasov" instead of "Remote"/Cluj/["Cluj", "Bucuresti", "Brasov"]

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#167]
ENVIROMENT: production
URL: https://solr.peviitor.ro
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Techtalent" Company
3. Check the jobs location for Senior Java Developer (remote is not a city in Romania), Product Validation Engineer (no city), Product Validation Engineer(Cluj/Bucuresti/Brasov is not a city in Romania)
4. Open https://www.techtalent.ro/careers
5. Check the jobs location for the 3 positions (Senior Java Developer,Product Validation Engineer, Product Validation Engineer)
EXPECTED RESULTS:
The location of the job must match the one in the job advert
Senior Java Developer, Remote
Product Validation Engineer, Remote (I propose Remote because on the company website there is no city)
Product Validation Engineer, ["Cluj", "Bucuresti", "Brasov"]

ACTUAL RESULTS:
The job location is "remote/no city/Cluj/Bucuresti/Brasov" instead of "Remote"/"Remote"/["Cluj", "Bucuresti", "Brasov"]
On the scrapers.peviitor.ro the messages "remote is not a city in Romania" , "no city" and "Cluj/Bucuresti/Brasov is not a city in Romania" are displayed

<img width="1100" alt="Screenshot 2023-10-28 155600_solr_remote" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/ef51e882-6033-40d2-affe-1a0439bcf320">
<img width="624" alt="Screenshot 2023-10-28 155740_solr_multiple cities" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/56f8aa82-295c-421a-9325-623854b1fe16">
<img width="1024" alt="Screenshot 2023-10-28 155920_solr_no city" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/03b70686-3182-4bff-8a80-735a5920eb8a">
<img width="1112" alt="Screenshot 2023-10-28 160051-techtalent_multiple cities" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/4607a333-2f92-4e7f-9611-ac9fe9afa82c">
<img width="1073" alt="Screenshot 2023-10-28 160303_techtalent_no city" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/b50894b6-b975-4e1f-b2dc-db67cb179b00">
<img width="1067" alt="Screenshot 2023-10-28 160638_techtalent_remote" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/400c7f23-f504-47b4-8275-32e24b4fc2b1">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, OK!
<img width="1112" alt="Screenshot 2023-11-10 213402" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/5fe2e1c6-bf1f-48b1-8150-d4442da22549">
