### ISSUE TITLE
Ddroidd - The message "Romania is not a city in Romania" is displayd on scrapers.peviitor.ro and the solr.peviitor.ro return 0 jobs after execute query

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#184]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Ddroidd" Company
3. Check the job titles
4. Open https://solr.peviitor.ro
5. Execute Query for "Ddroidd" Company

EXPECTED RESULTS:
The job locations are "Cluj-Napoca, Iasi or remote" as on the company's website
After executing the query, the returned answer is 7 jobs as on the company's website

ACTUAL RESULTS:
"Romania is not a city in Romania" is displayd on scrapers.peviitor.ro 
The solr,peviitor.ro return 0 jobs after execute query

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/e84c9718-3e34-4b57-bfef-e747341b4d2c)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/271a508b-cfc8-4fad-9b95-d20d7727c69f)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8ad39c77-785b-43b4-a6a8-e9951515364b)

**Comment by lalalaurentiu** [comment]
Fixed!
