### ISSUE TITLE
Fildas - The message "Bucuresti, Cluj, Satu Mare is not a city in Romania" is displayed

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#188]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Fildas" Company
3. Check the jobs location
4. Open https://solr.peviitor.ro
5. Execute Query for "Fildas" Company
6. Check the jobs location
7. Open https://www.fildas.ro/cariere and check the jobs location

EXPECTED RESULTS:
The job location is Bucuresti, Cluj, Satu Mare for the "Lucrator depozit farmaceutic " job, as on the company's website
The job location is Bucuresti, Cluj for the "Operator vanzari prin telefon" job, as on the company's website

ACTUAL RESULTS:
The messages "Bucuresti, Cluj, Satu Mare is not a city in Romania" and "Bucuresti, Cluj is not a city in romania" are displayd on scrapers.peviitor.ro 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/a79ac4c5-b1f0-4259-9d11-00bd9cbda90f)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/7cf91262-0c6f-4868-aa60-2da0207dba9d)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f3940f8b-7742-4b18-b2cf-32f5b678cb8e)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ee88b06a-ccd8-4b1d-80c2-598e927adfd6)

**Comment by lalalaurentiu** [comment]
Fixed!
