### ISSUE TITLE
Marquardt - Missing city for "Electronic Data Interchange Coordinator" and "SAP Key User for EWM" jobs

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#189]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Marquardt" Company
3. Execute filter query for "Electronic Data Interchange Coordinator" and  "SAP Key User for EWM" jobs
4. Check the city
5. Open https://marquardt-group.csod.com
6. Check the city of the jobs

EXPECTED RESULTS:
The city of the jobs is "Sibiu" as on the company's website

ACTUAL RESULTS:
The city is missing in on solr.peviitor.ro and on the scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/a7130ab0-4e52-4c96-ac25-26d348f20195)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/4bf252cb-4c95-4b41-9637-a74e4f03152a)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/7c125dd3-1668-47ae-b157-71774a33c7d7)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/3a80ef87-4730-4036-b70d-249442754930)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/1b2f333e-8a0d-4f30-b3ff-e08fd0cbb9bb)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The city of the jobs is "Sibiu" as on the company's website
