### ISSUE TITLE
Pirelli - The city is  "Slatina, Str. Draganesti 35" on solr.peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#190]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Pirelli" Company
3. Execute filter query for the "Tehnicieni mentenanta Slatina" job and check the city
4. Open https://corporate.pirelli.com
5. Check the city for the "Tehnicieni mentenanta Slatina" job

EXPECTED RESULTS:
The city of the jobs is "Slatina" as on the company's website

ACTUAL RESULTS:
The city is  "Slatina, Str. Draganesti 35" on solr.peviitor.ro
The message "Slatina, Str. Draganesti 35 is not a city in Romania" is displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/acf73128-fd4b-4bbe-9832-2b854cd7cb15)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/64be1a28-8c87-4de9-8e67-6ac5f6946cca)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/6aac0572-14cb-4df2-badb-64e326a7f2bb)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The city of the jobs is "Slatina" as on the company's website
