### ISSUE TITLE
Abbvie - The cities are "Timi&#x219;oara" and "United Kingdom" on solr.peviitor.ro for 2 of the jobs

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#191]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Abbvie" Company 
3. Check the cities of the jobs
4. Open scrapers.peviitor.ro and run scraper 
5. Check the locations of the jobs
6. Open https://careers.abbvie.com/en/search-jobs/Romania

EXPECTED RESULTS:
The cities of the jobs are: 
- Timișoara, Romania for "Product Specialist, Allergan Aesthetics" job
- Bucuresti, Romania for "Business Unit Manager Oncology" and "Senior Affiliate PV Partner Compliance Specialist" jobs

ACTUAL RESULTS:
The cities are "Timi&#x219;oara" and "United Kingdom" on solr.peviitor.ro for 2 of the jobs
The messages "Timișoara is not a city in Romania" and "United Kingdom is not a city in Romania" are displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/76398182-b8b4-457a-bc88-b7b0a46ceb1d)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/e4376559-7567-495d-83a7-e6bfc2a94fed)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/af00469f-488a-4607-9df7-dac14ceb59ec)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/dc9f284d-f8ae-4a15-af7b-a0ad0d644e38)

**Comment by lalalaurentiu** [comment]
Fixed!
