### ISSUE TITLE
Distri Gaz Sud Retele - The job locations is "Romania" instead of "Bucharest" or multiple location

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#233]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Distrigazsudretele" Company
3. Check the job locations
4. Open https://www.distrigazsud-retele.ro/cariere/posturi-disponibile
5. Check the job location 

EXPECTED RESULTS:
The job location is "Bucharest" or "București, Constanța, Brașov, Buzău, Galați, Târgu Jiu și Râmnicu Vâlcea" as on the company's website

ACTUAL RESULTS:
The job location is "Romania"
On the scrapers.peviitor.ro the message "Romania is not a city in Romania" is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/cc4acdfb-63f6-4c82-8e3c-1e88eb4422ee)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/6bc5f6cf-9016-4a08-986a-3699dda9d9d4)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f79dd16b-90ac-4750-8fa4-3f3f9ae8cdcb)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/5c30bbec-e608-4cf4-9b58-200983a1aeb4)

**Comment by lalalaurentiu** [comment]
Duplicate #262

**Comment by AdrianaCionca** [comment]
At the moment the company has no more positions available
