### ISSUE TITLE
Finastra - The city of the job is "Guadalajara, JAL" and "Lisbon" instead of "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#239]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Finastra" Company
3. Check the city of the jobs "Senior Agile Project Manager"  and "Software Developer"
4. Open https://careers.finastra.com/jobs
5. Check the city/location of the jobs

EXPECTED RESULTS:
The city of the jobs is "Bucharest" as on the company's website

ACTUAL RESULTS:
The city of the job "Senior Agile Project Manager" is "Guadalajara, JAL" instead of "Bucharest" on solr.peviitor.ro
The city of the job "Software Developer" is "Lisbon" instead of "Bucharest" on solr.peviitor.ro
The messages "Guadalajara, JAL is not a city in Romania" and "Lisbon is not a city in Romania" are displayed on scrapers.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/32152342-a1ab-48ea-8064-cdce9a51563d)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/3285e31a-b4ab-4309-bc0d-943988cf4fc2)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/c42270b0-3083-48e9-892d-fe8d3a8c0308)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/f481ac96-0400-497d-b649-fefdd2df9561)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the city of the jobs is "Bucharest" as on the company's website

![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/eadce114-4626-46d2-b8ae-7c5b39123a9d)



![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/81b5d2ad-062e-4f27-aaea-d843a9bfca4d)
