### ISSUE TITLE
Borgwarner - The company changed its logo

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#240]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Borgwarner" Company
3. Check the logo
4. Open https://www.tyrepress.com/2023/06/borgwarner-unveils-new-logo and check the logo

EXPECTED RESULTS:
The company logo is the same on scrapers.peviitor.ro as on the company website

ACTUAL RESULTS:
The company logo is not the same on scrapers.peviitor.ro as on the company website because the company changed its logo on July 12, 2023

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b75f45ff-3d3f-4ee6-8e6e-cc9bf19d3db5)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/acbeb057-050d-4248-aa1c-0c878319c706)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
After retesting, the company logo is the same on scrapers.peviitor.ro as on the company website

![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ad064ad1-80c5-4373-86a6-be1f9fb32bff)
