### ISSUE TITLE
United Kingdom is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#241]
Enivornment : production
Company : Xerox
URL : https://scrapers.peviitor.ro/
Browser : Mozilla Firefox
Device : Laptop
OS : Windows 10

Precondition : 
The site must be opened in browser.
Internet conections.

Steps to reproduce : 

1. Open the URL in the browser
2. Run scraper for "Xerox" Company
3. Check the city for "Commercial Pricing Manager "

EXPECTED RESULTS : 

The job must be located in Romania.
![xerox 2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/01b1c535-5e6a-45ea-aa00-7fe26b0572d8)

ACTUAL RESULTS : 

On the company site the job is located in IASI.

![xerox 1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/85c65020-8ab1-4618-826b-7c58449f5692)

**Comment by andbaldean** [comment]
@lalalaurentiu

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
The job's is remote.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/f50e7cf3-815e-4cb8-a37c-ae9eb957bf0e)
