### ISSUE TITLE
"Targetare" button is not working.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#242]
ENVIRONMENT: production
COMPANY : XEROX
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

   1. Open the URL in the browser
   2. Run scraper for : "Xerox" company.
   3. Go to the top and click " Targetare"
   
![Capture3](https://github.com/peviitor-ro/scrapers.js/assets/116546445/e2e6fb8e-cc0a-41d7-8cba-5ab647d1e238)

EXPECTED RESULTS : 

A new page is opened with the company name " Xerox" on "Targetare"

ACTUAL RESULTS : 

Is opened a blank page.

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro

**Comment by andbaldean** [comment]
The company does not have a link in targetare.ro

![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/407dd91e-ab73-41c1-9566-8fb6955541ea)
