### ISSUE TITLE
Heidelbergcement - Romania is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#243]
COMPANY : Heidelbergcement
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

    1.Open the URL in the browser
    2.Run scraper for " Heidelbergcement" Company
    3. Check the location for all the 7 jobs
    
EXPECTED RESULTS:
Jobs must have a city as a location

ACTUAL RESULTS:
The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for the following jobs:

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/8ad932f8-5474-4223-87b7-c36b27698092)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
Each posted job has a city as a location.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/1f605747-5290-46b2-9dbd-623755a8a6d0)
