### ISSUE TITLE
Yazaki - Missing city

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#244]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozzila Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for " Yazaki" Company
3.Check the location for all the 41 jobs

EXPECTED RESULTS:

Jobs must have a city as a location

ACTUAL RESULTS : 

 jobs missing city but on company site is Timisoara, Arad, Ploiesti.

![Capture3](https://github.com/peviitor-ro/scrapers.js/assets/116546445/a6743e55-56a3-4793-b76b-d28cc87930bd)
![Capture4](https://github.com/peviitor-ro/scrapers.js/assets/116546445/c6ec2bf6-5489-43fd-a38a-702e41f88aa3)
![Capture5](https://github.com/peviitor-ro/scrapers.js/assets/116546445/8151f6bc-6a4b-4c10-aa73-b4e7804cdc4e)
![Capture6](https://github.com/peviitor-ro/scrapers.js/assets/116546445/db1e1997-2088-45b3-ab88-cf74367b7287)
![Capture7](https://github.com/peviitor-ro/scrapers.js/assets/116546445/852fb6b4-78a1-490d-ac3f-1834d1681647)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
Each posted job has a city as a location.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/01ae0e82-ad6b-45a0-802c-efa45244aeea)
