### ISSUE TITLE
DrMax - Drobeta Turnu Severin is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#245]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for " Drmax" Company
3.Check the location for all the 83 jobs

EXPECTED RESULTS:
Jobs must have a city as a location

ACTUAL RESULTS:
Drobeta Turnu Severin is not a city in Romania
![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/1e0327a7-6a16-41c4-8b37-68234b4db341)

Sediul Central is not a city in Romania.
![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/a3be863c-ea64-4552-a3bd-85e157e18e9f)

Targu Mures is not a city in Romania,
![Capture3](https://github.com/peviitor-ro/scrapers.js/assets/116546445/96651f8c-6bbc-4904-998d-4d3c61df655d)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by andbaldean** [comment]
Each job has an assigned city.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/5870a8c6-a83d-452c-b418-6c13f3fd1b42)
