### ISSUE TITLE
Bearingpoint - Romania is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#246]
COMPANY : Bearingpoint
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser.
2. Run scraper for "Bearingpoint" company.
3. Check the location.

ACTUAL RESULTS : 

Jobs must have a city as a location.

EXPECTED RESULTS : 

The message "Romania is not a city in Romania" is displayed on scrapers.peviitor.ro for all 31 jobs.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/f3fe038b-a00a-4337-a7f5-d63025438ac2)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by andbaldean** [comment]
Each posted job has a city as a location.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/b246cabf-3c5d-4e2b-8432-df89fd6a0061)
