### ISSUE TITLE
CBRE - No city for the active jobs.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#247]
COMPANY : Cbre
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

    Open the URL in the browser.
    Run scraper for "Cbre" company.
    Check the location.

ACTUAL RESULTS :

Jobs must have a city as a location.

EXPECTED RESULTS :

9 jobs is active but has no city.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/04fdde8c-fcee-47a6-9091-d36205326592)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by andbaldean** [comment]
Each posted job has a city as a location.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/6e027c5b-54f9-425d-a8af-d13a4dc9528a)
