### ISSUE TITLE
Hella - Giarmata Timisoara is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#249]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Run scraper for " Hella" Company
3.Check the location for all the jobs

EXPECTED RESULTS:

Jobs must have a city as a location

ACTUAL RESULTS : 

Some jobs have the message : GIARMATA TIMISOARA in not a city in Romania.
![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/b4a6f479-79fc-4e23-a5ff-ee2a21db89b2)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by andbaldean** [comment]
Each posted job has a city as a location.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/e833b759-1a60-4db4-b66e-da1bed7ce4de)
