### ISSUE TITLE
Run scraper error.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#250]
ENVIROMENT: production
COMPANY: Aptiv
URL: https://scrapers.peviitor.ro/src/aptiv/index.html
Browser: Mozilla firefox
Device: laptop
OS: Windows 10

Precondition:
The site must be opened in Mozilla browser.

Steps:

    Click on "Run scraper".
   
Expected result:
The page is updated with active jobs.

Actual result:
Data.country is undefined message error.
![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/5489f866-023a-41a7-b2fc-a35d4c7e2ae1)

**Comment by lalalaurentiu** [comment]
There are no jobs available

![Image](https://github.com/peviitor-ro/scrapers.js/assets/67306273/681bcea4-4b1c-4468-8bf1-f035d7b47b7a)
