### ISSUE TITLE
QuanticLab - Run scraper error.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#252]
ENVIROMENT: production
COMPANY: Quanticlab
URL: https://scrapers.peviitor.ro/src/quanticlab/index.html
Browser: Mozilla firefox
Device: laptop
OS: Windows 10

Precondition:
The site must be opened in Mozilla browser.

Steps:

Click on "Run scraper".

Expected result:
The page is updated with active jobs.

Actual result:
Message error appears.
![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/a8a3e7c7-d890-485b-b780-687a558b1a2a)

**Comment by lalalaurentiu** [comment]
There are no jobs available

![Image](https://github.com/peviitor-ro/scrapers.js/assets/67306273/75490ff4-88f0-4fa1-b421-6aca7131fe0f)

**Comment by andbaldean** [comment]
Error still here.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/c3bbda22-5b82-4e2a-b614-aef8ae3f42b7)

**Comment by lalalaurentiu** [comment]
Scraper return errors because no jobs are available.
Come back to him when he has available jobs

**Comment by andbaldean** [comment]
There is no active jobs.

![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/e8c6a58c-70e3-46a5-97a0-3cc22aaff86a)
