### ISSUE TITLE
Run scraper error.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#253]
ENVIROMENT: production
COMPANY: Fildas
URL: https://scrapers.peviitor.ro/src/fildas/index.html
Browser: Mozilla firefox
Device: laptop
OS: Windows 10

Precondition:
The site must be opened in Mozilla browser.

Steps:

Click on "Run scraper".

Expected result:
The page is updated with active jobs.

Actual result:
Message error appears.
![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/966de9a7-946c-49d5-9dd4-7605c304ffc8)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
The page is updated with active jobs.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/90340274-72d8-4345-97fd-ead90548407c)
