### ISSUE TITLE
Targu Mures is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#254]
COMPANY : Hilti
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

    Open the URL in the browser.
    Run scraper for "Hilti" company.
    Check the location.

ACTUAL RESULTS :

Jobs must have a city as a location.

EXPECTED RESULTS :

Targu Mures is not a city in Romania is displayed for one job on scraper but on the company page the location is Targu Mures.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/11058fea-54ef-4581-b278-d4b2e71fa58c)

**Comment by lalalaurentiu** [comment]
Fixed!
