### ISSUE TITLE
Amdaris - Romania is not a city in Romania

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#258]
COMPANY : Amdaris
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser.
Run scraper for "Amdaris" company.
Check the location.

ACTUAL RESULTS :

Jobs must have a city as a location.

EXPECTED RESULTS :

romania is not a city in Romania is displayed.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/2e10f7d9-0300-4db1-a9fc-1dc92ba85384)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
Each posted job has a city as a location.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/a29ef326-1a8c-4816-bdd6-0104bd50f023)
