### ISSUE TITLE
Schaeffler - Herzogenaurach is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#259]
COMPANY : Schaeffler
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser.
Run scraper for "Schaeffler" company.
Check the location.

ACTUAL RESULTS :

Jobs must have a city as a location.

EXPECTED RESULTS :

Herzogenaurach is not a city in Romania is displayed on scraper
 but on the company page is Brasov.

![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/1e88aa81-6829-4523-a68f-0c4f1cfc1769)

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/361a89ad-1154-40e8-b47a-129279115358)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
Each posted job has a city as a location.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/2654fa1e-6337-483d-8353-17bd0ffcafb6)
