### ISSUE TITLE
Schaeffler - There is no "Targetare" button.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#260]
ENVIRONMENT: production
COMPANY : Schaeffler
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

    Open the URL in the browser
    Run scraper for : "Schaeffler" company.
    Go to the top and click " Targetare"

EXPECTED RESULTS :

A new page is opened with the company name " Schaeffler" on "Targetare"

ACTUAL RESULTS :

There is no "Targetare" button.

![Capture5](https://github.com/peviitor-ro/scrapers.js/assets/116546445/9fe44098-5550-4c0c-a5b1-0e034dd5a6af)

**Comment by lalalaurentiu** [comment]
the company is not present on targetare.ro
