### ISSUE TITLE
"See jobs" not working.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#261]
ENVIRONMENT: production
COMPANY : Cocacolahbc
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

    Open the URL in the browser
    Run scraper for : "Cocacolahbc" company.
   Click "See jobs".

ACTUAL RESULTS : 

Active jobs is listed on peviitor.ro.

EXPECTED RESULTS : 

There is no active jobs.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/730fa1ca-8962-4fb6-80d4-69dd890a6380)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
Active jobs is listed on peviitor.ro.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/56803102-35e5-4683-98bf-65cb1b939162)
