### ISSUE TITLE
DistriGazSudRetele - Romania is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#262]
COMPANY : DistriGazSudRetele
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser.
Run scraper for "DistriGazSudRetele" company.
Check the location.

ACTUAL RESULTS :

Jobs must have a city as a location.

EXPECTED RESULTS :

Romania is not a city in Romania is displayed.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/4107cd66-d50f-4755-be8b-27ebd9ab6bcd)

**Comment by lalalaurentiu** [comment]
the company has no more jobs available
