### ISSUE TITLE
Tg Mures is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#263]
COMPANY : Groupama
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser.
Run scraper for "Groupama" company.
Check the location.

ACTUAL RESULTS :

Jobs must have a city as a location.

EXPECTED RESULTS :

Tg Mures is not a city in Romania.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/3bbb422b-3b48-4638-a620-4265afac1f18)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
Tg Mures is a city from Romania and the job is located in a city in Romania.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/87e0d5e1-0c6e-4ce7-8dd1-9363d81dd1a9)
