### ISSUE TITLE
Targetare button not available.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#266]
ENVIRONMENT: production
COMPANY : Pentasia
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Run scraper for : "Pentasia" company.
Go to the top and click " Targetare"

EXPECTED RESULTS :

A new page is opened with the company name " Pentasia" on "Targetare"

ACTUAL RESULTS :

There is no "Targetare" button.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/8bb5cf0b-fb59-44a2-a7b5-3ad99bd8843b)

**Comment by lalalaurentiu** [comment]
The company does not have a link in targetare.ro

**Comment by andbaldean** [comment]
The company does not have a link in targetare.ro.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/dfa8592b-d16c-4312-8042-fa373183ed16)
