### ISSUE TITLE
Waiting to long for response.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#268]
ENVIRONMENT: production
COMPANY : Henkel
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Run scraper for : "Henkel" company.

EXPECTED RESULTS :

A list with active jobs is opened.

ACTUAL RESULTS :

A response with error is displayed.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/ca6e55b9-50a8-4dc1-9c66-9e7089c0b0a4)

**Comment by lalalaurentiu** [comment]
Duplicate #87
