### ISSUE TITLE
SLB logo update.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#269]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Run scraper for "SLB" Company
Check the logo

EXPECTED RESULTS:
The company logo is the same on scrapers.peviitor.ro as on the company website

ACTUAL RESULTS:
The company logo is not the same on scrapers.peviitor.ro as on the company website

![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/e103e5a0-552c-4797-8d42-ace4d39aa334)
![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/29086a6d-0064-41af-80c6-f484bd0f43f3)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
The company logo has been updated.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/f82529fe-f6c8-42d8-b1c7-c1667e189d98)
![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/a9a71a4f-26f9-44de-ad2d-9bca2019ea07)
