### ISSUE TITLE
PENTALOG logo update.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#270]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser
Run scraper for "Pentalog" Company
Check the logo

EXPECTED RESULTS:
The company logo is the same on scrapers.peviitor.ro as on the company website

ACTUAL RESULTS:
The company logo is not the same on scrapers.peviitor.ro as on the company website

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/ca49d044-bb58-43e5-b0fc-bf512b8dd5da)
![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/b8978f22-79de-4457-88b2-6d6a3e13528e)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by andbaldean** [comment]
The company's logo has been updated .

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/8839b685-8dd0-4b69-9ceb-f6591482da40)
![Capture2](https://github.com/peviitor-ro/scrapers.js/assets/116546445/2a3f73cf-93e3-42a5-8e1a-b6792f934bb6)
