### ISSUE TITLE
Mahle - RO is not a city in Romania.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#271]
COMPANY : Mahle
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Mozilla Firefox
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

Open the URL in the browser.
Run scraper for "Mahle" company.
Check the location.

ACTUAL RESULTS :

Jobs must have a city as a location.

EXPECTED RESULTS :

RO is not a city in Romania.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/c4df9bd3-64e3-4969-98d9-509e85f2c6fe)

**Comment by lalalaurentiu** [comment]
job is no longer available
