### ISSUE TITLE
Schneiderelectric - Run scraper error.

### ISSUE THREAD

**Issue by andbaldean** [peviitor-ro/scrapers.js#272]
ENVIROMENT: production
COMPANY: Schneiderelectric
URL: https://scrapers.peviitor.ro/src/schneiderelectric/index.html
Browser: Mozilla firefox
Device: laptop
OS: Windows 10

Precondition:
The site must be opened in Mozilla browser.

Steps:

Click on "Run scraper".

Expected result:
The page is updated with active jobs.

Actual result:
Message error appears.

![Capture1](https://github.com/peviitor-ro/scrapers.js/assets/116546445/c82dc3c8-b11d-4f7f-a2e6-d460e87e064e)

**Comment by lalalaurentiu** [comment]
I don't see any problems
