### ISSUE TITLE
Cognizantsoftvision - All jobs posted on scrapers.peviitor.ro are on site and have multiple locations instead of being remote as on the company website

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#297]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Search for "Cognizantsoftvision" company and run the scraper
  3. Check the Location and the Job Type
  4. Open https://www.cognizantsoftvision.com/job-search/?location=romania
  5. Check the Job Type in the job description

EXPECTED RESULTS:
 All the 15 jobs posted on scrapers.peviitor.ro are with the possibility of working remotely, as on the company website

ACTUAL RESULTS:
All jobs posted on scrapers.peviitor.ro have multiple locations: Baia Mare, București, Cluj-Napoca, Iași, Timișoara 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/0a60ea7a-125e-4f77-a598-0c7115d020bc)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/266ebfc1-dfce-4c88-994c-55344ae43d4f)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, All the 17 jobs posted on scrapers.peviitor.ro are with the possibility of working remotely or hybrid as on the company website.


![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/d400efed-108b-499a-bb6c-607fa6677289)
