### ISSUE TITLE
Crowdstrike - The location/city of the job is "Romania" for 2 jobs

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#298]
ENVIRONMENT: production
URL: solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute Query for "Crowdstrike" Company
3. Check the city of the jobs
4. Open https://scrapers.peviitor.ro
5. Run scraper for "Crowdstrike" Company
6. Check the location for the jobs: "Sr. Backend Engineer (Remote) " and "Intelligence Analyst Intern (Remote)"

EXPECTED RESULTS:
The job location is "Bucharest" or the location space remains empty because the job is remote

ACTUAL RESULTS:
 The city of the job is "Romania" for 2 jobs: "Sr. Backend Engineer (Remote) " and "Intelligence Analyst Intern (Remote)"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/aa9ea349-7e84-4b99-ad2b-029395484041)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/4c76ca74-01d6-4144-9bef-7511d379d7d1)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2e7785c4-beb7-43a5-983b-4b3045f3c24f)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, the location space remains empty because the job is remote

![Image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/249688f7-5dcc-4f6c-a64b-bf882c54a0b7)
