### ISSUE TITLE
Ey - The number of jobs posted on Peviitor (48) and the one returned by the API (47) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#33]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Ey" in the search bar.
3. Check the number of jobs available for Ey.
4. Run "Ey" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_js/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 48 while the number of jobs returned by the API is 47.

![ey peviitor](https://github.com/peviitor-ro/scrapers.js/assets/134513404/b14b9e81-7e01-4fd7-a00a-e2455c8854a1)

![ey scraper](https://github.com/peviitor-ro/scrapers.js/assets/134513404/6b85c9d5-7e9d-4b1b-afdf-934f6c248f58)

**Comment by Codetamer333** [comment]
The issue resolved itself now the numbers match.
