### ISSUE TITLE
NPX - The number of jobs posted on Peviitor (8) and the one returned by the API (87) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#34]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "NPX" in the search bar.
3. Check the number of jobs available for NPX.
4. Run "NPX" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_js/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 8 while the number of jobs returned by the API is 87.

![npx peviitor](https://github.com/peviitor-ro/scrapers.js/assets/134513404/4e9d7851-f062-457c-8681-2682f2313495)

![npx scraper](https://github.com/peviitor-ro/scrapers.js/assets/134513404/47117986-5d98-4e1b-9761-dc7f280af2a6)

**Comment by Codetamer333** [comment]
Hella was repaired at 20:15, when all scrapers start it should work just fine.

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting NPX company is no longer available


![Image](https://github.com/peviitor-ro/scrapers.js/assets/72222644/549eccef-5595-41b3-8e99-4b6db2e03531)
