### ISSUE TITLE
Hella - The number of jobs posted on Peviitor (31) and the one returned by the API (34) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#35]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Hella" in the search bar.
3. Check the number of jobs available for Hella.
4. Run "Hella" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_js/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 31 while the number of jobs returned by the API is 34.

![hella peviitor](https://github.com/peviitor-ro/scrapers.js/assets/134513404/164ecb4b-2186-4dc3-904f-547ad33d784a)

![hella scraper](https://github.com/peviitor-ro/scrapers.js/assets/134513404/e9af0573-41a2-4450-80ba-897eb7561f02)

**Comment by Codetamer333** [comment]
Hella was repaired at 20:15, when all scrapers start it should work just fine.

**Comment by Ale230992** [comment]
The number of jobs posted on Peviitor (140) and the one returned by the API (140) IS the same.
Fixed. Closed issue.
