### ISSUE TITLE
Glovo - The number of jobs returned by the API (21) and the one posted on the Glovo company website (23) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#37]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Run "Glovo" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_js/".
2. Check the number of jobs displayed.
3. Open "https://jobs.glovoapp.com/find-your-ride/?l=romania" in the browser.
4. Check the number of jobs available for Glovo.

EXPECTED RESULTS:
The number of jobs returned by the API and the one posted on the Glovo company website should be the same.

ACTUAL RESULT:
The number of jobs returned by the API (21) and the one posted on the Glovo company website (23) isn't the same.

![glovo scraper](https://github.com/peviitor-ro/scrapers.js/assets/134513404/c6642956-7984-4df7-9359-78c7c0b2431f)

![glovo site](https://github.com/peviitor-ro/scrapers.js/assets/134513404/22b0a1f4-2cb8-4292-95fb-384d68f42504)

**Comment by lalalaurentiu** [comment]
The scraper works fine, the problem occurs when filtering the data by glovo which brings 2 more Jobs from Barcelona.

-Marketing & Growth Associate Director - SEE (They/She/He) -> is in Barcelona Spain
<img width="1440" alt="Screenshot 2023-10-12 at 12 25 42" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/beaee019-3281-4a67-b848-acf08562c110">

- Regional Head of Brands Ads (They/She/He) -> is in Barcelona Spain
<img width="1440" alt="Screenshot 2023-10-12 at 12 25 05" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/d9d4295b-3871-4644-9625-ef178453e644">

<img width="1440" alt="Screenshot 2023-10-12 at 12 26 55" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/baccb9d2-5b63-4ee4-b4e7-0000cfb929dc">
<img width="1440" alt="Screenshot 2023-10-12 at 12 29 22" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/4c994bf7-b920-4f81-9af1-0bfbf7f80886">

**Comment by AdiVanca** [comment]
After retesting the number of jobs is the same.( 26 returned by scraper, 26 on glovo website for romania + 1 from barcelona)
