### ISSUE TITLE
RABEN - The number of jobs posted on Peviitor (7) and the one posted on the company website (13) isn't the same.

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#38]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Mozilla FireFox
Device: desktop
OS: Windows 11

STEPS TO REPRODUCE:

Open "https://peviitor.ro/" in the browser.
Type "Raben" in the search bar.
Check the number of jobs available for Raben.
Open "https://romania.raben-group.com/cariere". 
Click on image "Pozitii la birou", open "https://romania.raben-group.com/cariere/pozitii-la-birou" 
Count the number of jobs displayed.
Turn back to "https://romania.raben-group.com/cariere".
Click on image "Pozitii in depozit", open "https://romania.raben-group.com/cariere/lucratori-in-depozit"
Count the number of jobs displayed.
Calculate total.

EXPECTED RESULT:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 7 jobs posted on Peviitor website while on the company website there are posted 13 available jobs in total.
![peviitor_raben_7jobs](https://github.com/peviitor-ro/based_scraper_py/assets/118441061/026673ff-9971-4b1b-9553-d8dc2b9037a1)
![Raben_13 joburi_Screenshot 2023-09-21 085958](https://github.com/peviitor-ro/based_scraper_py/assets/118441061/d06c1bcc-5644-4af1-b9c0-21de4d33f39b)
![Raben1_10joburi_Screenshot 2023-09-21 090045 - Copy (2)](https://github.com/peviitor-ro/based_scraper_py/assets/118441061/90bf6f77-f1de-4ced-84bf-bd40ff301fc9)
![Raben2_3joburi_Screenshot 2023-09-21 090111 - Copy](https://github.com/peviitor-ro/based_scraper_py/assets/118441061/c79e34a7-af61-4fe7-a4aa-3527c5a1c9fe)

**Comment by sebiboga** [comment]
can you please retest? I re-run the scraper; I fixed the issue in SOLR

**Comment by DanaCatavei** [comment]
Bug was fixed
![Screenshot 2023-09-26 083853](https://github.com/peviitor-ro/scrapers.js/assets/118441061/6e0b621a-4b7d-495b-b2ca-7cc2203a1ec6)
![Screenshot 2023-09-26 083915](https://github.com/peviitor-ro/scrapers.js/assets/118441061/3f520815-2e20-413d-a54b-3a85df4eb81d)
![Screenshot 2023-09-26 084052](https://github.com/peviitor-ro/scrapers.js/assets/118441061/a0e949f5-ba03-495c-a299-e3e74b07506d)
![Screenshot 2023-09-26 084104](https://github.com/peviitor-ro/scrapers.js/assets/118441061/48c8456e-fd4b-43d7-895c-1e980422c3cb)
