### ISSUE TITLE
"Mondelez" company - scraper doesn't work 

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/scrapers.js#396]
URL: https://admin.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser.
2. Click on "Scraperi".
3. Click on "scrapers.js".
4. Enter "Mondelez" in the search bar.
5. Select "mondelez.js".
6. Click on "Ruleaza".

EXPECTED RESULTS:
The scraper should run without issues.

ACTUAL RESULTS:
An error occurs.

![image](https://github.com/user-attachments/assets/0d558b4c-5fea-418c-99f7-b325ffc48e2b)

**Comment by lalalaurentiu** [comment]
fixed

**Comment by Lore78** [comment]
Fixed!

![image](https://github.com/user-attachments/assets/66fd12bc-2771-431b-8b11-22a08c4cd314)
