### ISSUE TITLE
Preh - The number of jobs posted on Peviitor (3) and the one posted on the company website (9) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#42]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Preh" in the search bar.
3. Check the number of jobs available for Preh.
4. Open "https://career.preh.com/en/job-openings/current-job-offers.html".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 3 jobs posted on Peviitor website while on the company website there are posted 9 available jobs.

![preh peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/8477d248-e5d5-4954-adb2-07bb7ef0379a)

![preh site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/2ac4b562-f365-40fe-a416-d137bd07cde8)

**Comment by lalalaurentiu** [comment]
I don't think there is any problem!
<img width="1440" alt="Screenshot 2023-09-29 at 06 53 58" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/7c9e6f50-8c27-4e69-b5d5-a0d9f6a83322">
<img width="1440" alt="Screenshot 2023-09-29 at 06 54 16" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/b506fb54-6ba0-40c1-b121-eeb3d00383ef">

**Comment by DanaCatavei** [comment]
Nu este rezolvat bug-ul. Exista diferente intre numarul de job-uri de pe site-ul peviitor.ro (5), scrapers.peviitor (5 )si site-ul firmei (10). (job-uri valabile pentru Romania in Ghimbav si Iasi. Trebuie selectate orasele, pe rand)
<img width="1067" alt="Screenshot 2023-11-02 134118" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/39002942-d334-4c01-9132-e5530576cb89">
<img width="1077" alt="Screenshot 2023-11-02 134135" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/3bc4da20-071f-4e49-a5ab-fc67709e9795">
<img width="1089" alt="Screenshot 2023-11-02 134358" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/1fdf4e27-d081-4044-bdd3-9d9c30ba1ba1">
