### ISSUE TITLE
SyncROSoft - The number of jobs posted on Peviitor (7) and the one posted on the company website (6) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#43]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "SyncROSoft" in the search bar.
3. Check the number of jobs available for SyncROSoft.
4. Open "https://www.sync.ro/jobs.html".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 7 jobs posted on Peviitor website while on the company website there are posted 6 available jobs.

![syncrosoft peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/13c44a83-c63c-420d-b620-7daa45f5447f)

![syncrosoft site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/26a31cc9-8974-4473-a77a-b02f13db534e)

**Comment by lalalaurentiu** [comment]
I don't think there is any problem!
<img width="1440" alt="Screenshot 2023-09-29 at 07 01 39" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/1f0c38ab-adb4-437c-9d0f-27e100fa60d6">
<img width="1440" alt="Screenshot 2023-09-29 at 07 01 57" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/4867073e-69d2-4859-89e9-4f3e7db6b4a4">

**Comment by VACostin** [comment]
> ACTUAL RESULT:
There are 7 jobs posted on Peviitor website while on the company website there are posted 6 available jobs.

We're updating the jobs every 24 hours,
What happened most likely is: Job delisted on Syncrosoft website on 18 Sep (now listing 6 jobs) > On peviitor there were still 7 jobs displayed > Peviitor runs the daily update on 19 Sep > Now Peviitor also displays 6 jobs.
