### ISSUE TITLE
Agricover - The number of jobs posted on Peviitor (23) and the one posted on the company website (33) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#44]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Agricover" in the search bar.
3. Check the number of jobs available for Agricover.
4. Open "https://agricover.ro/cariere".
5. Count the number of jobs displayed (there are 33 of them).

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 23 jobs posted on Peviitor website while on the company website there are posted 33 available jobs.

![agricover peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/fc9c3c8d-09cd-4a1e-ab80-555cb674ac9e)

![agricover site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/d71963b2-e849-4102-adfa-66ff9afbe283)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the number of jobs posted on peviitor.ro and the one  posted on company website are the same (15)
