### ISSUE TITLE
NPX - The number of jobs posted on Peviitor (8) and the one posted on the company website (79) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#45]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "NPX" in the search bar.
3. Check the number of jobs available for NPX.
4. Open "https://nxp.wd3.myworkdayjobs.com/careers?Location_Country=f2e609fe92974a55a05fc1cdc2852122".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 8 jobs posted on Peviitor website while on the company website there are posted 79 available jobs.

![npx peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/66aa05c4-fe11-4936-83d3-edc0d9b7922a)

![npx site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/e5d85e45-a724-4f26-8ba9-eb9acbb1e458)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting NPX company is no longer available


![Image](https://github.com/peviitor-ro/scrapers.js/assets/72222644/922f210b-a713-40cc-aff9-e3dff22e4936)
