### ISSUE TITLE
Evolve - The number of jobs posted on Peviitor (20) and the one posted on the company website (28) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#46]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Evolve" in the search bar.
3. Check the number of jobs available for Evolve.
4. Open "https://recrutare.evolvetoday.ro/jobs".
5. Count the number of jobs displayed.

EXPECTED RESULT:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 20 jobs posted on Peviitor website while on the company website there are posted 28 available jobs.

![evolve peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/f1d16c22-128b-4f77-8f00-8dbb91426d20)

![evolve site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/980db5b9-b0f7-4e6b-9f06-021e8df49203)

**Comment by lalalaurentiu** [comment]
Fixed!
