### ISSUE TITLE
Mahle - The number of jobs posted on Peviitor (12) and the one posted on the company website (15) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scrapers.js#47]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Mahle" in the search bar.
3. Check the number of jobs available for Mahle.
4. Open "https://careers.mahle.com/?optionsFacetsDD_country=RO&locale=en_US".
5. Count the number of jobs displayed.

EXPECTED RESULT:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs posted on the company website should be the same.

ACTUAL RESULT:
There are 12 jobs posted on Peviitor website while on the company website there are posted 15 available jobs.

![mahle peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/e90881d5-8f77-4764-9983-213dbd136772)

![mahle site](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/1312c7de-5ea9-4b93-87ae-44d4bded9783)

**Comment by lalalaurentiu** [comment]
I don't think there is any problem!
<img width="1440" alt="Screenshot 2023-09-29 at 07 16 25" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/684274d2-ca16-460b-ba7e-6cc3fabfbbd2">
<img width="1440" alt="Screenshot 2023-09-29 at 07 16 39" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/01e6215d-c206-45e0-99b0-0c6d2db231bb">
<img width="1440" alt="Screenshot 2023-09-29 at 07 17 00" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/d7533051-ef03-4c1f-af91-a8c069cea00a">

**Comment by AdiVanca** [comment]
After retesting the number of jobs are the same on peviitor.ro(6) and on company website(6)


![Image](https://github.com/peviitor-ro/scrapers.js/assets/72222644/265d1438-ef48-4547-a60b-6006a9a0b085)
