### ISSUE TITLE
SII - The number of jobs posted on scrapers.peviitor.ro (20) and the one posted on the company website (31) isn't the same

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#48]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

  1.  Open URL "https://scrapers.peviitor.ro/" in browser
  2.  Type "sii" in the search bar
  3.  Click on the sii folder
  4.  Click on the "Run Scraper" button
  5.  See that 20 jobs are listed on https://scrapers.peviitor.ro/src/sii/index.html
  6.  Click on the "Sii Careers" button to open the SII website with the listed jobs (https://www.siiromania.ro/jobopportunities/) 
  7.  See that there are 2 job pages
  8.  Count the jobs displayed on the first page 
  9.  Count the jobs displayed on the second page
 10.  Calculate the total number of jobs on both pages
EXPECTED RESULTS:
The number of job listings displayed on scrapers.peviitor.ro should match the number of job listings available on the SII website

ACTUAL RESULTS:
The number of job listings on scrapers.peviitor.ro after pressing Run Careers button differs from the number of job listings available on the SII website.
<img width="1087" alt="SII_site_page1_1Screenshot 2023-09-29 135439" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/bfcc1963-4054-4f18-b979-dc819bc0f50e">
<img width="1120" alt="SII-page1_2_2023-09-29_14h15_50" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/11e2950d-bca6-4d0d-adaf-4d86668c2762">
<img width="1120" alt="SII_site_page2_1_2023-09-29_14h18_15" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/8351eeb0-2292-4c06-87e7-2ca972b5cbdb">
<img width="1120" alt="SII_page2_2_2023-09-29_14h20_51" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/b0da9c37-89bf-4db2-8e26-301b8ff8cc03">

**Comment by DanaCatavei** [comment]
<img width="1043" alt="SII_api_Screenshot 2023-09-29 135339" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/bd4599f7-9cde-4a3a-adee-5448bbfba794">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
I retested and it's ok
<img width="1100" alt="Screenshot 2023-10-13 225133_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/3ab28a17-bc72-465d-8452-e9ebe1758574">
