### ISSUE TITLE
SII - The number of jobs posted on peviitor.ro (20) and the one posted on the company website (31) isn't the same

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#49]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

  1.  Open URL "https://scrapers.peviitor.ro/" in browser
  2.  Type "sii" in the search bar
  3.  Click on the sii folder
  4.  Click on the "See jobs" button to open peviitor.ro website (https://peviitor.ro/rezultate?q=sii&country=Rom%C3%A2nia&page=1)
  5.  See that 20 jobs are listed on peviitor.ro website
  6.  Return to the web page with the URL https://scrapers.peviitor.ro/
  7.  Click on the "Sii Careers" button to open the SII website with the listed jobs (https://www.siiromania.ro/jobopportunities/) 
  8.  See that there are 2 job pages
  9.  Count the jobs displayed on the first page 
  10.  Count the jobs displayed on the second page
 11.  Calculate the total number of jobs on both pages
EXPECTED RESULTS:
The number of job listings displayed on peviitor.ro should match the number of job listings available on the SII website

ACTUAL RESULTS:
The number of job listings on peviitor.ro differs from the number of job listings available on the SII website.
<img width="1053" alt="SII_peviitor_Screenshot 2023-09-29 135353" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/1a6d44bb-77d6-442e-b731-9c96d072afa8">
<img width="1087" alt="SII_site_page1_1Screenshot 2023-09-29 135439" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/7e02562c-a437-4299-b2ef-ea2aa5d28455">
<img width="1120" alt="SII-page1_2_2023-09-29_14h15_50" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/92332104-aaaa-4dde-b6b5-b0c83596bb84">
<img width="1120" alt="SII_site_page2_1_2023-09-29_14h18_15" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/5e99cee3-3914-41a4-a1fa-4bfc110dcc1e">
<img width="1120" alt="SII_page2_2_2023-09-29_14h20_51" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/eaaa1ebf-b087-43d2-9b99-7174b8fc559a">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
I tested it and it's ok
<img width="1059" alt="Screenshot 2023-10-13 224234" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/40a46023-2e5a-446b-b509-26e29eab6b17">
