### ISSUE TITLE
Regnology invalid logo

### ISSUE THREAD

**Issue by TheMrM** [peviitor-ro/scrapers.js#5]
** ENVIREMENT **

DEV: firme.peviitor.ro
LINK URL: https://firme.peviitor.ro/
BROWSER: Chrome Version 114

** STEPS TO REPRODUCE **

1)Open url in browser
2)Search for company

** EXPECTED RESULTS **

Company should have a logo displayed on DEV enviroment.

** ACTUAL RESULTS **

It shows "Logo not found"

![regnology](https://github.com/peviitor-ro/based_scraper_js/assets/128375812/af8eb998-90ba-4390-882b-a8960504bd30)

The url that the scraper uses is invalid

![regnology404](https://github.com/peviitor-ro/based_scraper_js/assets/128375812/6b9cbb5f-4b15-4666-9799-ac5966f284b7)

**Comment by Codetamer333** [comment]
Rezolvat
