### ISSUE TITLE
Halliburton - The number of jobs posted on scrapers.peviitor.ro (10) have wrong locality

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#50]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

  1.  Open URL "https://scrapers.peviitor.ro/" in browser
  2.  Type "halliburton" in the search bar
  3.  Click on the Halliburton folder
  4.  Click on the "Run Scraper" button
  5.  See that the 10 jobs listed on https://scrapers.peviitor.ro/src/halliburton/index.html have the wrong locality
  6.  Click on the "Halliburton Careers" button to open the Halliburton website with the listed jobs (https://jobs.halliburton.com/search/?createNewAlert=false&q=&locationsearch=romania) 
  7.  See that there are no job for Romania
 
EXPECTED RESULTS:
The number of job listings displayed on scrapers.peviitor.ro should match the number of job listings available on the Halliburton website

ACTUAL RESULTS:
The number of job listings on scrapers.peviitor.ro after pressing Run Careers button differs from the number of job listings available on the Halliburton  website for Romania.
<img width="1117" alt="Screenshot 2023-10-02 172539" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/a094d197-c529-429c-ab72-2bd271b2e98f">
<img width="1120" alt="2023-10-02_17h27_32" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/48a092c7-c190-4017-9a72-4b6b3c9d4327">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
I retested and it's ok
<img width="967" alt="Screenshot 2023-10-13 224557_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/66333b2e-9338-4ed1-b42a-73cf743c0999">
<img width="1094" alt="Screenshot 2023-10-13 224710_Halliburton" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/41bf5feb-baa1-4262-a812-535906113b5f">
