### ISSUE TITLE
Regnology - the subtitle 'Romania' is included in the title

### ISSUE THREAD

**Issue by IonutFlorinBosca** [peviitor-ro/scrapers.js#51]
ENVIRONMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

    1. Open "https://peviitor.ro/" in the browser.
    2. Type "Regnology" in the search bar.
    3. Click on any of the jobs listed
    4. Notice how the title and the subtitle are displayed within the job listing

EXPECTED RESULT:
When searching for "Regnology" and displaying their job openings the title and the subtitle should display correctly.

ACTUAL RESULT:
The subtitle "Romania" is attached at the end of the title for every job opening on "https://peviitor.ro/"

![subtitle-within-the-title](https://github.com/peviitor-ro/scrapers.js/assets/98032042/26c2f319-f558-4357-ba35-cfa62bf3f9d2)
![job-listed-regnology](https://github.com/peviitor-ro/scrapers.js/assets/98032042/356de171-c45d-492c-b00a-222a74b24782)

**Comment by lalalaurentiu** [comment]
Fixed!
