### ISSUE TITLE
Unilever - Different job location (Romania instead of Bucharest) - all 3 jobs

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#52]
ENVIRONMENT: production
URL: https://solr.peviitor.ro/solr/#/jobs/query?q=company:%22unilever%22&q.op=OR&indent=true&rows=65&useParams=
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "Unilever" company and check the location/city for all 3 jobs

EXPECTED RESULTS:
The location of the job is the city of Bucharest, as is the company website

ACTUAL RESULTS:
The location of the job is Romania

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/55109026-11ab-465b-a09c-9b93ad205fec)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/b5d989ba-4d1e-4048-8e6b-6adedc97b1bb)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/97ffbdc3-4391-4cc9-a11a-f32681eaf5fb)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/428d9013-bdac-4f8a-9c42-3d852771359c)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The location of the job is the city of Bucharest, as is the company website
