### ISSUE TITLE
WNS - The number of jobs on solr.peviitor.ro (6 jobs) is not the same as the number of jobs on the company website (11 jobs)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#54]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "WNS" company and check the number of jobs
  3. Open the "WNS" website and check the number of jobs

EXPECTED RESULTS:
The number of jobs on solr.peviitor.ro is the same as the number of jobs on the company website

ACTUAL RESULTS:
The number of jobs on solr.peviitor.ro (6 jobs) is not the same as the number of jobs on the company website (11 jobs)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/0c7a2ce6-c152-478c-8c57-b885b0bc2111)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/9dc11d71-ac2a-4d8b-ab02-01f89f21e715)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/013b1158-c2e7-4972-af05-9007406f2578)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The number of jobs on solr.peviitor.ro is the same as the number of jobs on the company website
