### ISSUE TITLE
WNS - The job "Procurement with French" is remote instead of on-site in Bucharest

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#55]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "WNS" company and check the job location
  3. Open the "WNS" website and check the job location

EXPECTED RESULTS:
The job is on-site in Bucharest

ACTUAL RESULTS:
The job "Procurement with French" is remote instead of on-site in Bucharest

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/29fcd380-fa5d-467f-958c-a123d0baf4e2)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ec1ba8a2-df96-4dfc-a306-e28d5350b749)

**Comment by lalalaurentiu** [comment]
Fixed!
