### ISSUE TITLE
JW-Marriott - The number of jobs posted on peviitor.ro (0) and the one posted on the company website (7) isn't the same

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#57]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/marriott/index.html
Browser: Chrome
Device: desktop
OS: Windows 11

STEPS TO REPRODUCE:

  1.  Open URL in browser
  2.  Click "See Jobs" button
  3.  See that no jobs are listed on peviitor.ro website
  4.  Open https://jobs.marriott.com/marriott/jobs
  5.  Type "Romania" in the search field and click Enter.
  6.  Check the number of jobs displayed.
EXPECTED RESULTS:
The number of job listings displayed on peviitor should match the number of job listings available on the Marriott website

ACTUAL RESULTS:
The number of job listings on peviitor.ro
 differs from the number of job listings available on the Marriott website. There are no jobs on the site peviitor.ro and the jobs listed on Merriott's website are 7.

![Screenshot 2023-10-06 222222_peviitor](https://github.com/peviitor-ro/scrapers.js/assets/118441061/6b18326c-2b7a-4984-9102-09f9b38e4c16)
![Screenshot 2023-10-06 221133_pagina marriott careers](https://github.com/peviitor-ro/scrapers.js/assets/118441061/2c47550b-a850-4384-ac14-d5b67b2f41ed)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
I tested it and it's ok
<img width="1120" alt="2023-10-13_12h20_06" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/66775648-9908-4e7b-aa61-261151eac2c5">
