### ISSUE TITLE
Autoliv - The number of jobs posted on scrapers.peviitor.ro (20) and the one posted on the company website (46) isn't the same

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#58]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/autoliv/index.html
Browser: Chrome
Device: desktop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "Run Scraper" button
3. See that 20 jobs are listed in the jobs section
4. Click on the "Autoliv Careers" button to open the Autoliv website with the listed jobs (https://careerromania.autoliv.com/jobs)
5. See that there are 3 job pages
6. Count the jobs displayed in the 3 pages
7. Calculate the total number of jobs
EXPECTED RESULTS:
The number of job listings displayed on the URL page should match the number of job listings available on the Autoliv website
ACTUAL RESULTS:
The number of job listings on the URL page, after pressing Run Careers button, differs from the number of job listings available on the Autoliv website.

![Screenshot 2023-10-06 224300_scraper](https://github.com/peviitor-ro/scrapers.js/assets/118441061/c428bba3-f1a3-4f2c-b0f3-3c0502d194ec)
![Screenshot 2023-10-06 225336_autoliv career pag1](https://github.com/peviitor-ro/scrapers.js/assets/118441061/cb6e39c6-67ff-4efd-b65a-1f47f594908d)
![Screenshot 2023-10-06 225351_autoliv career pag2](https://github.com/peviitor-ro/scrapers.js/assets/118441061/4a0925f5-4629-4775-8c10-696565889fe2)
![Screenshot 2023-10-06 225400__autoliv career pag3](https://github.com/peviitor-ro/scrapers.js/assets/118441061/2adb5dad-19ec-48f5-b037-e204ba3a8679)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
it's ok now!
<img width="1111" alt="Screenshot 2023-10-15 212025_autoliv" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/c5814d75-8a84-4232-99ea-20feb5329b2b">

<img width="1112" alt="Screenshot 2023-10-15 212607_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/97effb3f-509e-4750-8879-2caba4a25a6e">
