### ISSUE TITLE
Autoliv - The number of jobs posted on peviitor.ro (20) and the one posted on the company website (46) isn't the same

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#59]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/autoliv/index.html
Browser: Chrome
Device: desktop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "See jobs" button to open peviitor.ro website (https://peviitor.ro/rezultate?q=autoliv&country=Rom%C3%A2nia&page=1)
3. See that 20 jobs are listed on peviitor.ro website
4. Return to the web page with the URL
5. Click on the "Autoliv Careers" button to open the Autoliv website with the listed jobs (https://careerromania.autoliv.com/jobs)
6. See that there are 3 job pages
7. Count the jobs displayed in the 3 pages
7. Calculate the total number of jobs
EXPECTED RESULTS:
The number of job listings displayed on peviitor.ro should match the number of job listings available on the Autoliv website
ACTUAL RESULTS:
The number of job listings on peviitor.ro differs from the number of job listings available on the Autoliv website.
![Screenshot 2023-10-06 224313_peviitor](https://github.com/peviitor-ro/scrapers.js/assets/118441061/b88ff4bc-bfbc-49d3-a02d-688bb3963d8c)
![Screenshot 2023-10-06 225336_autoliv career pag1](https://github.com/peviitor-ro/scrapers.js/assets/118441061/c5f05df3-3d0d-49e8-a4cf-731f7929fed8)
![Screenshot 2023-10-06 225351_autoliv career pag2](https://github.com/peviitor-ro/scrapers.js/assets/118441061/5db3acd5-f055-469f-a007-2dd7deaa8219)
![Screenshot 2023-10-06 225400__autoliv career pag3](https://github.com/peviitor-ro/scrapers.js/assets/118441061/43722840-718c-4111-8c5b-838b660c0a72)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
now it's ok!
<img width="1111" alt="Screenshot 2023-10-15 212025_autoliv" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/dd20bd0e-428a-4b2a-b420-49dcb89a5eb4">
<img width="1069" alt="Screenshot 2023-10-15 212111_peviitor" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/1843ddff-c046-4270-a438-bd804f0009b7">
