### ISSUE TITLE
Autoliv - Incorrect locality for the displayed jobs on scrapers.peviitor.ro page

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#60]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/autoliv/index.html
Browser: Chrome
Device: desktop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open URL in browser
2. Click on the "Run Scraper" button
3. See that 20 jobs are listed on peviitor.ro website with the incorrect location, namely Romania.
4. Click on the "Autoliv Careers" button to open the Autoliv website with the listed jobs (https://careerromania.autoliv.com/jobs)
5. See that there are 3 pages with the names of the jobs containing the locality
EXPECTED RESULTS:
The jobs must be posted with the correct locality
ACTUAL RESULTS:
The jobs are posted with incorrect locality, namely Romania.
![Screenshot 2023-10-06 224300_scraper_locations](https://github.com/peviitor-ro/scrapers.js/assets/118441061/8a6fc247-8bf5-47d2-9ecb-211cb71bdd46)
![Screenshot 2023-10-06 225336_autoliv career pag1_locations](https://github.com/peviitor-ro/scrapers.js/assets/118441061/814f3811-d365-4531-9b67-176664b4d90f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
the localities are ok for all jobs!
<img width="1112" alt="Screenshot 2023-10-15 212607_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/ea44dce0-017b-49a0-ae13-b2079d1c6c9e">
