### ISSUE TITLE
 No City - AGRICOVER 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#63]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2.  Run query for the "Agricover" company
  3. Go to the job "Manager zonă Nord-Vest" and check the location/city
  4. Open the job on the company website and check the location of the job  - https://agricover.ro/cariere/manager-zona-nv

EXPECTED RESULTS:
The location of the job is Oradea/Satu Mare as on the company website

ACTUAL RESULTS:
The job location/city is missing

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/86a2aabb-9f26-4e64-bf4e-8af8d505e541)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/3d6759bb-476e-4d15-aa45-c2bf1c84d82b)

**Comment by lalalaurentiu** [comment]
Fixed!
