### ISSUE TITLE
Agricover - Typo in company description

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#65]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Search for "Agricover" Company and look at the description
  3. Open https://agricover.ro/cariere and check the description

EXPECTED RESULTS:
The description of the company is the same in scrapers.peviitor.ro as on the company website

ACTUAL RESULTS:
 An "S" was added to the word "Agricover", on the first line of the description

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/7a64eff3-7c15-4c66-89c3-6c3dd222de2b)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/7c246e29-a8b9-4e38-83c8-77f5ed7c0857)

**Comment by lalalaurentiu** [comment]
This section will be deprecated
