### ISSUE TITLE
Maersk - Instead of the city, the message "Romania is not a city in Romania" is written

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#66]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Search for "Maersk" Company and check the job location/city 
  3. Open https://maersk.wd3.myworkdayjobs.com/Maersk_Careers/job/RO and check the job location/city 

EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website

- LCL Delivery Agent - Bucharest
- Customer Experience Consultant - Bucharest
- Electrical Engineer - Bucharest
- Financial Operations Delivery Agent - Constanta
- Customer Experience Consultant - Bucharest
- Deck Cadet - Constanta

ACTUAL RESULTS:
Instead of the city, the message "Romania is not a city in Romania" is written

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/85b4d2a5-faad-431e-9674-0bbd3e4fde63)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The city of the job is written in accordance with the city on the company website
