### ISSUE TITLE
Ey -  Instead of the city the message "Chisinau is not a city in Romania" is written

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#67]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Search for "Ey" Company and check the job location/city 
  3. Open https://careers.ey.com/ey/job/Chisinau-Senior-Auditor-Chisinau-Hybrid-2012/836030101/ and check the job location/city 

EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website

ACTUAL RESULTS:
Instead of the city, the message "Chisinau is not a city in Romania" is written

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/64b61ae6-8d86-4451-b8d1-48add4e6a8cf)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/42efb114-3c27-4ad4-b513-2f14e7b9a619)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The city of the job "Chisinau" is written in accordance with the city on the company website
