### ISSUE TITLE
Ey - The location of the jobs is Bucharest instead of remote

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#69]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Ey" Company
3. Check the Job location for the jobs
4. Open https://careers.ey.com/ey/job and check the jobs locations

EXPECTED RESULTS:
The jobs are remote as on the company website

ACTUAL RESULTS:
The following jobs are located in Bucharest instead of remote

Senior Financial Auditor - Hybrid 
External Audit Manager 
Audit Consultant (with Audit/Accounting experience) - Hybrid 
Senior Financial Due Diligence 
Junior Consultant - Climate Change and Sustainability Services (Hybrid) 
Senior Consultant Direct Taxes ( Anywhere in Country )
Market Research Analyst (Designing Surveys) 
Senior Lawyer Banking, Finance, Digital & Tech Law 
Senior Consultant Financial Accounting Advisory 
Senior Cybersecurity Analyst - SOC L2 Analyst (24/7 coverage) (Anywhere in Country )
Data Analyst Team Lead
Senior Forensic Specialist (Financial Auditors - Hybrid) 
Senior Auditor FSI - Hybrid 

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/2744bd6c-9bb7-4c22-8f44-04f111e093cb)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/368666b9-a2bd-49dd-bb9c-e43beaa37aea)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The jobs are remote as on the company website
