### ISSUE TITLE
Nxp - The company name is misspelled (NPX instead NXP)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#70]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Check the company name with "Npx"
3. Open https://www.nxp.com and check the company name
4. Open https://scrapers.peviitor.ro/src/npx/index.html and check the company name

EXPECTED RESULTS:
The company name is NXP

ACTUAL RESULTS:
The company name is NPX

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/069727bd-1e99-43f3-a17a-3739af1f87f1)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/923b02f4-c0b7-4f0a-a119-e654d25df248)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ac93d637-91ef-4715-a7a0-4e370af8ad95)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The "NXP Careers" button is misspelled

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/e4821a1c-325f-422d-9cfc-3bebc9640405)

**Comment by AdrianaCionca** [comment]
The company name has been corrected
