### ISSUE TITLE
Nxp - The number of jobs with the Bucharest location in solr.peviitor.ro(117) is not the same as the number of jobs on the company's website (120)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#71]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute query for Nxp company with Bucharest city
3. Check the number of jobs
4. Open https://nxp.wd3.myworkdayjobs.com/en-US/careers?locations
5. Check the number of jobs with Bucharest as the location

EXPECTED RESULTS:
The number of jobs is the same

ACTUAL RESULTS:
The number of jobs with the Bucharest location in solr.peviitor.ro(117) is not the same as the number of jobs on the company's website (120)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/66c4a236-19f5-4807-8635-d84e24a46d36)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/97f0c648-7770-4754-8a0c-81de8d9ae8e0)

**Comment by AdrianaCionca** [comment]
UPDATE 11.10.2023

ACTUAL RESULTS:
The number of jobs with the Bucharest location on solr.peviitor.ro(118) is not the same as the number of jobs on the company's website (121)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/7441659e-1086-4a11-8fb6-40fd35cea50b)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/925cbae6-1027-4b01-beaf-e05019dfdb74)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The number of jobs in solr.peviitor.ro is  the same as the number of jobs on the company's website
