### ISSUE TITLE
Alten -  Instead of remote, the message "No Job Type" is displayed for jobs that have instead of locality the message "Remote is not a city in Romania"

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#72]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/alten/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check the job type section and job location/city
4. Open https://careers.altenromania.ro/ and check the job type
EXPECTED RESULTS:
City is not mandatory, instead the job type must be remote.
[Joburi remote Alten.xlsx](https://github.com/peviitor-ro/scrapers.js/files/12861905/Joburi.remote.Alten.xlsx)

ACTUAL RESULTS:
Instead of Remote the message "No Job Type" is displayed, instead of the city, the message "Remote is not a city in Romania" is written.
 
<img width="1120" alt="2023-10-10_21h47_01_alten" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/d6ee8c38-1a30-4d19-8c51-e82a65f21451">
[Joburi Alten & locatii.xlsx](https://github.com/peviitor-ro/scrapers.js/files/12861916/Joburi.Alten.locatii.xlsx)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat, OK!
![Screenshot 2023-10-23 154629](https://github.com/peviitor-ro/scrapers.js/assets/118441061/a76ebe23-e80d-442b-841a-0c1a11a90c40)
