### ISSUE TITLE
Alten - Instead of the city the message "Cluj Napoca is not a city in Romania" is written 

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#73]
ENVIRONMENT: production
URL:  https://scrapers.peviitor.ro/src/alten/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check the job location/city for job "Mainframe Production Engineer"
4. Open https://careers.altenromania.ro/ and click the "See More" button 6 times
5. Check the job location for job "Mainframe Production Engineer" from the Alten website
EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website

ACTUAL RESULTS:
Instead of the city, the message "Cluj Napoca is not a city in Romania" is written
<img width="1097" alt="Screenshot 2023-10-11 002837" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/6e3506fa-ee85-4d99-9e75-53c26abb2cf7">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat! 
<img width="1014" alt="Screenshot 2023-10-21 221626" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/740dc2cd-db48-407d-83e1-a4e4c0ee3f6d">
