### ISSUE TITLE
Nxp - Job location - "2, 3 or 12 Locations"  instead "Bucharest"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#74]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Execute Query for "Nxp" Company and check the job location/city 
  3. Open https://nxp.wd3.myworkdayjobs.com and check the job location

EXPECTED RESULTS:
The city of the job is Bucharest like on the company website

- Principal Radar System SW Architect 
- Product Manager (m/f/d)
- Stacks SW Developer - NCG 

ACTUAL RESULTS:
 "city":["2 Locations"]  instead of "Bucharest"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/72095f50-82e3-4ca0-b4da-0ce4df5acbc2)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/61030ed2-6461-426a-8c5d-bb1f8bb51bae)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/3e29425a-8eea-4790-88d7-f7df96590456)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/06a3a668-f1ae-4dde-a3b9-c9e22773db4e)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8fd96338-d6c7-479e-83e6-95f82fd6e9cd)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/32c4345b-627b-4aff-bfe2-53ae36be30aa)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The city of the job is Bucharest like on the company website
