### ISSUE TITLE
Nxp - 13 of the 139 jobs on Scraper-UI are from the Czech Republic, not from Romania

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#75]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Search for  "Nxp" Company and check the job location/city 
  3. Open https://nxp.wd3.myworkdayjobs.com and check the job location

EXPECTED RESULTS:
All 139 jobs from Scraper-UI are located in Romania

ACTUAL RESULTS:
13 of the 139 jobs on Scraper-UI are from the Czech Republic, not from Romania

- 6 jobs - "Student - Ethernet SW developper" 
- 3 jobs - "Intern SW Quality"
- 2 jobs - "Machine Learning Student/Intern NPX"
- 2 jobs - "Advanced Analog SW Developer - Intern NPX"

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/4921fbdd-d8bb-4818-8bb7-e353ed502aa6)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/07897757-90fc-461a-ad39-b2b268d59b78)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/c18355ee-5a73-4a87-be1c-fb3303c2c408)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
All  jobs from Scraper-UI are located in Romania
