### ISSUE TITLE
Crowdstrike -  "city":["2 Locations"] instead Remote

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#76]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Execute Query for "Crowdstrike" Company and check the job location/city 
  3. Open https://crowdstrike.wd5.myworkdayjobs.com and check the job location

EXPECTED RESULTS:
The jobs are remote

ACTUAL RESULTS:
 "city":["2 Locations"] instead of Remote

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/a5dff685-f9b6-42ec-84d8-d06e4d82d1a8)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/8d32c20a-1977-47e3-8552-c71d420f17a3)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The jobs have 2 locations, remote and Bucharest
