### ISSUE TITLE
Crowdstrike - The number of jobs on solr.peviitor.ro(3) is not the same as the number of jobs on the company's website (4)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#77]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute query for Crowdstrike company
3. Check the number of jobs
4. Open https://crowdstrike.wd5.myworkdayjobs.com
5. Check the number of jobs 

EXPECTED RESULTS:
The number of jobs is the same

ACTUAL RESULTS:
The number of jobs on solr.peviitor.ro (3) is not the same as the number of jobs on the company's website (4)
The job "UI Framework Engineer (Remote)" is not on solr.peviitor.ro

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/a9e6a52d-2d69-4cfd-b67b-5b7a8fac4fd2)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/52a46d73-1d01-4769-acfc-a6ac82472cae)
![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/9592acb7-c346-4a3e-9578-67e4613e26b3)

**Comment by lalalaurentiu** [comment]
Fixed!
