### ISSUE TITLE
  Infineon - The number of jobs posted on solr.peviitor.ro(21) is not the same as the number of jobs posted on the company's website (29)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#79]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute query for "Infineon" Company
3. Check the number of jobs
4. Open https://www.infineon.com/cms/en/careers
5. Check the number of jobs available in Romania

EXPECTED RESULTS:
The number of jobs is the same

ACTUAL RESULTS:
The number of jobs posted on solr.peviitor.ro(21) is not the same as the number of jobs posted on the company's website (29)
-   4 Jobs Brasov
- 21 Jobs Bucharest
-   4 Jobs Iasi

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/348f41f3-6af9-4766-abb0-7934f87b242f)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/37912756-03fa-4358-a37e-ac18a9ba356f)

**Comment by lalalaurentiu** [comment]
I did not identify any problem with the scraper, it returned the same number of jobs
<img width="1440" alt="Screenshot 2023-10-19 at 07 21 43" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/96b0465c-b0ae-4ff5-9232-df5ccf385f16">
<img width="1440" alt="Screenshot 2023-10-19 at 07 21 55" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/302d27c8-53ef-4f96-907c-7786dc813fb4">

The jobs in Brasov and Iasi are included in Romania
<img width="1440" alt="Screenshot 2023-10-19 at 07 25 55" src="https://github.com/peviitor-ro/scrapers.js/assets/67306273/c4d8a71d-26e0-4aa3-9682-4a7f28957a5d">

**Comment by AdrianaCionca** [comment]
The number of jobs posted on solr.peviitor.ro is the same as the number of jobs posted on the company's website
