### ISSUE TITLE
Brinks - The number of jobs posted on solr.peviitor.ro(9) is not the same as the number of jobs posted on the company's website (8)

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scrapers.js#80]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Execute query for "Brinks" Company
3. Check the number of jobs
4. Open https://ro.brinks.com/ro/careers/career-positions
5. Check the number of jobs available 

EXPECTED RESULTS:
The number of jobs is the same

ACTUAL RESULTS:
The number of jobs posted on solr.peviitor.ro(9) is not the same as the number of jobs posted on the company's website (8)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/ce52422b-6eb7-4db3-a1d0-e6d1cc818d6f)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdrianaCionca** [comment]
The number of jobs posted on solr.peviitor.ro is the same as the number of jobs posted on the company's website
