### ISSUE TITLE
Smithfield - Instead of the city, the message "Romania is not a city in Romania" is written

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#91]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/smithfield/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check location/city for all jobs
4. Open https://www.smithfield.ro/ro/cariere/posturi-disponibile and check the job location/city
EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website
ACTUAL RESULTS:
Instead of the city, the message "Romania is not a city in Romania" is written

Manager Finisher Farm - Timisoara, Timis
Sef de echipa (Departament Constructii) - Timisoara, Timis
Operator introducere, validare si prelucrare date (divizia FERME) - Timisoara, Timis
Electrician interior Abatorul din Freidorf - Timisoara, Timis
Gestionar Depozit (Materiale Auxiliare) - Timisoara, Timis
Tractorist FNC Padureni - Padureni, Timis
Conducator Auto Transport Rutier de Marfuri - Timisoara, Timis
Responsabil SSM/PSI - Timisoara, Timis
Electrician Auto - Timisoara, Timis
Senior Buyer - Timisoara, Timis
Tehnician Junior Echipamente de Calcul si Retele - Timisoara, Timis
Electrician/Lacatus mecanic/Electromecanic - Timisoara, Timis
Financial Analyst - Timisoara, Timis
AP Accountant - Timisoara, Timis

Note: I deduced the location from the ad. It could not be done automatically.

<img width="1097" alt="Screenshot 2023-10-13 210838" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/13f687c6-25fd-42d1-9203-0246ce31925c">

**Comment by DanaCatavei** [comment]
Errata: the jobs with the corresponding localities should have been put in the EXPECTED RESULTS area

EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website

Manager Finisher Farm - Timisoara, Timis
Sef de echipa (Departament Constructii) - Timisoara, Timis
Operator introducere, validare si prelucrare date (divizia FERME) - Timisoara, Timis
Electrician interior Abatorul din Freidorf - Timisoara, Timis
Gestionar Depozit (Materiale Auxiliare) - Timisoara, Timis
Tractorist FNC Padureni - Padureni, Timis
Conducator Auto Transport Rutier de Marfuri - Timisoara, Timis
Responsabil SSM/PSI - Timisoara, Timis
Electrician Auto - Timisoara, Timis
Senior Buyer - Timisoara, Timis
Tehnician Junior Echipamente de Calcul si Retele - Timisoara, Timis
Electrician/Lacatus mecanic/Electromecanic - Timisoara, Timis
Financial Analyst - Timisoara, Timis
AP Accountant - Timisoara, Timis

Note: I deduced the location from the ad. It could not be done automatically.

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat! Este Ok acum.
![Screenshot 2023-10-22 225431](https://github.com/peviitor-ro/scrapers.js/assets/118441061/08cc02ea-862c-4e33-96bc-cb8dc422e2a5)
