### ISSUE TITLE
Bandainamco - It is duplicated on the website https://scrapers.peviitor.ro

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#92]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro
Browser: Chrome
Device: laptop
OS: Windows 11

STEPS TO REPRODUCE:

  1.  Open URL in browser
  2.  Search for "bandainamco" company
  3.  Check the names of the two folders listed, which are almost identical
  4.  Click on "bandainamcoent" folder
  5.  See that it has no logo, no link to the company's website and it has the same job as the "bandainamco" company
  6.  Go back to the previous page where the two folders are displayed
  4.  Click on "bandainamco" folder
  5.  See that the logo is ok, the link to the company's homepage is ok (https://www.bandainamcoent.ro/ro/careers/) and the same job is listed 

EXPECTED RESULTS:
The company "bandainamco" appears only once after the search on the https://scrapers.peviitor.ro website

ACTUAL RESULTS:
The company "bandainamco" appears twice in the search on the https://scrapers.peviitor.ro website
<img width="1030" alt="Screenshot 2023-10-13 214641" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/22478bf5-55f3-4e21-8ff6-0ef16eb0fd20">
<img width="1040" alt="Screenshot 2023-10-13 214754_NotOK" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/30d54ed3-fd7c-4470-a8e0-ee67b7652378">
<img width="1062" alt="Screenshot 2023-10-13 214834_OK" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/8af6b16c-cf4d-491b-a349-e6d5184bf98d">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat! Este Ok acum!
![Screenshot 2023-10-22 230049](https://github.com/peviitor-ro/scrapers.js/assets/118441061/0a583833-c35d-422b-b272-67173dcdba33)
