### ISSUE TITLE
Bandainamco - Instead of the city, the message "Romania is not a city in Romania" is written

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#93]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/bandainamco/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Click on the "Run Scraper" button
3. Check location/city for the job
4. Open https://www.bandainamcoent.ro/ro/careers/ and check the job location/city
EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website
Senior C++ Game Programmer, Bucuresti
Note: I deduced the location from the ad. It could not be done automatically.

ACTUAL RESULTS:
Instead of the city, the message "Romania is not a city in Romania" is written
<img width="969" alt="Screenshot 2023-10-13 223225_Romania is not a city" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/4fdf760a-bbe0-405d-894b-1cde01f96816">
<img width="1102" alt="Screenshot 2023-10-13 223353_site-ul_firmei" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/574ba9fd-13ca-46c6-8625-68bec8d2d87b">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat! Este OK acum!
![Screenshot 2023-10-22 230404_city](https://github.com/peviitor-ro/scrapers.js/assets/118441061/91bd9865-9b62-4a34-91b1-7459615166db)
