### ISSUE TITLE
SLB - Instead of the city the message "Aricestii-Rahtivani is not a city in Romania" is written 

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#97]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/slb/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Click on the "Run Scraper" button
3.Check the location/city for jobs where "Aricestii-Rahtivani is not a city in Romania" appears
4.Open https://careers.slb.com/job-listing and filter by "Romania"
5.Check the job location for jobs in the city of "Aricestii-Rahtivani" from the SLB website
EXPECTED RESULTS:
The city of the job is written in accordance with the city on the company website
Electronics Technician, Aricestii-Rahtivani, județul Prahova
Equipment Operator, Aricestii-Rahtivani, județul Prahova
Equipment Operator, Aricestii-Rahtivani, județul Prahova
WIS Field Specialist, Aricestii-Rahtivani, județul Prahova
WIS Field Specialist, Aricestii-Rahtivani, județul Prahova
Electronic Technician Trainee ,Aricestii-Rahtivani, județul Prahova
Electronic Technician Trainee, Aricestii-Rahtivani, județul Prahova
Mechanical Technician Trainee, Aricestii-Rahtivani, județul Prahova
Mechanical Technician Trainee, Aricestii-Rahtivani, județul Prahova
WCF Cementing Specialist, Aricestii-Rahtivani, județul Prahova

ACTUAL RESULTS:
Instead of the city, the message "Aricestii-Rahtivani is not a city in Romania" is written
<img width="1096" alt="Screenshot 2023-10-16 014349_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/133fd0b0-4422-43e3-a355-8f3f1c90ec27">
<img width="1075" alt="Screenshot 2023-10-16 014503_slb" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/a7f51068-0b93-410a-8497-1c0fa09e6685">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat! Este Ok acum. 
![Screenshot 2023-10-23 151825](https://github.com/peviitor-ro/scrapers.js/assets/118441061/2a0c29ea-eaf7-4e00-9f91-4958648367e9)
