### ISSUE TITLE
SLB - Discrepancy between the number of jobs displayed by both the scraper and the company's website (41) and the actual number of jobs (40)

### ISSUE THREAD

**Issue by DanaCatavei** [peviitor-ro/scrapers.js#98]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/slb/index.html
Browser: Chrome
Device: Laptop
OS: Windows 11

STEPS TO REPRODUCE:

1.Open the URL in the browser
2.Click on the "Run Scraper" button
3.Check the job title and location/city for last job in the list
4.Open https://careers.slb.com/job-listing and filter by "Romania"
5.Count the jobs for Romania
EXPECTED RESULTS:
The number of jobs to be in concordance with the number of jobs listed on the company's website (40)
Note: see joburi_slb.xls
[joburi_slb.xlsx](https://github.com/peviitor-ro/scrapers.js/files/12910857/joburi_slb.xlsx)

ACTUAL RESULTS:
Discrepancy between the number of jobs displayed by both the scraper and the company's website (41) and the actual number of jobs (40)
<img width="1031" alt="Screenshot 2023-10-16 014843_jobs_nbr_scraper" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/22fcdd45-5909-4c1f-ad85-123f92d96817">
<img width="1120" alt="2023-10-16_01h51_39_41leajob" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/f1828555-a806-4c6b-84e9-57bc5cc0d402">
<img width="1120" alt="2023-10-16_01h54_34_joburi_slb" src="https://github.com/peviitor-ro/scrapers.js/assets/118441061/bcb7cbe1-18c3-4481-8668-18effd2039b4">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by DanaCatavei** [comment]
Verificat! Este ok acum!
![Screenshot 2023-10-23 152104_scraper](https://github.com/peviitor-ro/scrapers.js/assets/118441061/786ca7dd-9b66-4918-9c8e-8573de5798ce)
![Screenshot 2023-10-23 152328_slb](https://github.com/peviitor-ro/scrapers.js/assets/118441061/8bc4f2a2-68b8-47bb-b4b4-e288c8501752)
